// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Coinbase.OpenApiClients.Cdp.Models
{
    /// <summary>
    /// Composed type wrapper for classes <see cref="global::Soenneker.Coinbase.OpenApiClients.Cdp.Models.AbiFunction"/>, <see cref="global::Soenneker.Coinbase.OpenApiClients.Cdp.Models.AbiInput"/>
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class AbiItem : IComposedTypeWrapper, IParsable
    {
        /// <summary>Composed type representation for type <see cref="global::Soenneker.Coinbase.OpenApiClients.Cdp.Models.AbiFunction"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Coinbase.OpenApiClients.Cdp.Models.AbiFunction? AbiFunction { get; set; }
#nullable restore
#else
        public global::Soenneker.Coinbase.OpenApiClients.Cdp.Models.AbiFunction AbiFunction { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::Soenneker.Coinbase.OpenApiClients.Cdp.Models.AbiInput"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Coinbase.OpenApiClients.Cdp.Models.AbiInput? AbiInput { get; set; }
#nullable restore
#else
        public global::Soenneker.Coinbase.OpenApiClients.Cdp.Models.AbiInput AbiInput { get; set; }
#endif
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Coinbase.OpenApiClients.Cdp.Models.AbiItem"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Coinbase.OpenApiClients.Cdp.Models.AbiItem CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            var mappingValue = parseNode.GetChildNode("type")?.GetStringValue();
            var result = new global::Soenneker.Coinbase.OpenApiClients.Cdp.Models.AbiItem();
            if("AbiFunction".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
            {
                result.AbiFunction = new global::Soenneker.Coinbase.OpenApiClients.Cdp.Models.AbiFunction();
            }
            else if("AbiInput".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
            {
                result.AbiInput = new global::Soenneker.Coinbase.OpenApiClients.Cdp.Models.AbiInput();
            }
            return result;
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            if(AbiFunction != null)
            {
                return AbiFunction.GetFieldDeserializers();
            }
            else if(AbiInput != null)
            {
                return AbiInput.GetFieldDeserializers();
            }
            return new Dictionary<string, Action<IParseNode>>();
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            if(AbiFunction != null)
            {
                writer.WriteObjectValue<global::Soenneker.Coinbase.OpenApiClients.Cdp.Models.AbiFunction>(null, AbiFunction);
            }
            else if(AbiInput != null)
            {
                writer.WriteObjectValue<global::Soenneker.Coinbase.OpenApiClients.Cdp.Models.AbiInput>(null, AbiInput);
            }
        }
    }
}
#pragma warning restore CS0618
