// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Coinbase.OpenApiClients.Cdp.Models
{
    /// <summary>The type of webhook event.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum AcceptancePaymentSessionVoidSucceededEventType
    {
        [EnumMember(Value = "acceptance.payment_session.void_succeeded")]
        #pragma warning disable CS1591
        AcceptancePaymentSessionVoidSucceeded,
        #pragma warning restore CS1591
    }
}
