// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Coinbase.OpenApiClients.Cdp.Models
{
    /// <summary>The type of the Account.- `prime`: a linked Coinbase Prime account.- `business`: a linked Coinbase Business account.- `cdp`: a CDP-native account created via this API. Used for accounts created on  behalf of an Entity and for Customer-owned accounts.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum AccountType
    {
        [EnumMember(Value = "prime")]
        #pragma warning disable CS1591
        Prime,
        #pragma warning restore CS1591
        [EnumMember(Value = "business")]
        #pragma warning disable CS1591
        Business,
        #pragma warning restore CS1591
        [EnumMember(Value = "cdp")]
        #pragma warning disable CS1591
        Cdp,
        #pragma warning restore CS1591
    }
}
