// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Coinbase.OpenApiClients.Cdp.Models
{
    /// <summary>
    /// A request to adjust an existing borrow position for an end user&apos;s smart account on the specified borrow product.The request can supply collateral, withdraw collateral, repay debt, and/or borrow more of the loan asset, broadcasting a user operation to apply the changes onchain.A single request must not combine `addCollateralAmount` with `removeCollateralAmount` or `repayLoanAmount`, and must not combine `borrowLoanAmount` with `repayLoanAmount` or `removeCollateralAmount`. Otherwise any subset of the four amount fields may be supplied; at least one is required.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class AdjustBorrowPositionRequest : IAdditionalDataHolder, IParsable
    {
        /// <summary>A positive decimal string without scientific notation or whitespace.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? AddCollateralAmount { get; set; }
#nullable restore
#else
        public string AddCollateralAmount { get; set; }
#endif
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>A positive decimal string without scientific notation or whitespace.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? BorrowLoanAmount { get; set; }
#nullable restore
#else
        public string BorrowLoanAmount { get; set; }
#endif
        /// <summary>The globally unique ID of the borrow product, which is a UUID prefixed with the string `bp_`.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? BorrowProductId { get; set; }
#nullable restore
#else
        public string BorrowProductId { get; set; }
#endif
        /// <summary>Optional paymaster metadata forwarded to the configured paymaster service. Valid only when a paymaster is configured via `useCdpPaymaster: true` or a `paymasterUrl`.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Coinbase.OpenApiClients.Cdp.Models.AdjustBorrowPositionRequestPaymasterContext? PaymasterContext { get; set; }
#nullable restore
#else
        public global::Soenneker.Coinbase.OpenApiClients.Cdp.Models.AdjustBorrowPositionRequestPaymasterContext PaymasterContext { get; set; }
#endif
        /// <summary>A valid HTTP or HTTPS URL.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? PaymasterUrl { get; set; }
#nullable restore
#else
        public string PaymasterUrl { get; set; }
#endif
        /// <summary>A positive decimal string without scientific notation or whitespace.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? RemoveCollateralAmount { get; set; }
#nullable restore
#else
        public string RemoveCollateralAmount { get; set; }
#endif
        /// <summary>A positive decimal string without scientific notation or whitespace.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? RepayLoanAmount { get; set; }
#nullable restore
#else
        public string RepayLoanAmount { get; set; }
#endif
        /// <summary>Whether to use the CDP Paymaster for the user operation. When `true`, `paymasterUrl` must not be set.</summary>
        public bool? UseCdpPaymaster { get; set; }
        /// <summary>The ID of the Temporary Wallet Secret that was used to sign the X-Wallet-Auth header.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? WalletSecretId { get; set; }
#nullable restore
#else
        public string WalletSecretId { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Coinbase.OpenApiClients.Cdp.Models.AdjustBorrowPositionRequest"/> and sets the default values.
        /// </summary>
        public AdjustBorrowPositionRequest()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Coinbase.OpenApiClients.Cdp.Models.AdjustBorrowPositionRequest"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Coinbase.OpenApiClients.Cdp.Models.AdjustBorrowPositionRequest CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Coinbase.OpenApiClients.Cdp.Models.AdjustBorrowPositionRequest();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "addCollateralAmount", n => { AddCollateralAmount = n.GetStringValue(); } },
                { "borrowLoanAmount", n => { BorrowLoanAmount = n.GetStringValue(); } },
                { "borrowProductId", n => { BorrowProductId = n.GetStringValue(); } },
                { "paymasterContext", n => { PaymasterContext = n.GetObjectValue<global::Soenneker.Coinbase.OpenApiClients.Cdp.Models.AdjustBorrowPositionRequestPaymasterContext>(global::Soenneker.Coinbase.OpenApiClients.Cdp.Models.AdjustBorrowPositionRequestPaymasterContext.CreateFromDiscriminatorValue); } },
                { "paymasterUrl", n => { PaymasterUrl = n.GetStringValue(); } },
                { "removeCollateralAmount", n => { RemoveCollateralAmount = n.GetStringValue(); } },
                { "repayLoanAmount", n => { RepayLoanAmount = n.GetStringValue(); } },
                { "useCdpPaymaster", n => { UseCdpPaymaster = n.GetBoolValue(); } },
                { "walletSecretId", n => { WalletSecretId = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("addCollateralAmount", AddCollateralAmount);
            writer.WriteStringValue("borrowLoanAmount", BorrowLoanAmount);
            writer.WriteStringValue("borrowProductId", BorrowProductId);
            writer.WriteObjectValue<global::Soenneker.Coinbase.OpenApiClients.Cdp.Models.AdjustBorrowPositionRequestPaymasterContext>("paymasterContext", PaymasterContext);
            writer.WriteStringValue("paymasterUrl", PaymasterUrl);
            writer.WriteStringValue("removeCollateralAmount", RemoveCollateralAmount);
            writer.WriteStringValue("repayLoanAmount", RepayLoanAmount);
            writer.WriteBoolValue("useCdpPaymaster", UseCdpPaymaster);
            writer.WriteStringValue("walletSecretId", WalletSecretId);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
