// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Coinbase.OpenApiClients.Cdp.Models
{
    /// <summary>The name of a capability. Capabilities represent granular functional permissionsthat determine what actions a customer can perform. Each capability must beexplicitly requested before use.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum CapabilityName
    {
        [EnumMember(Value = "custodyCrypto")]
        #pragma warning disable CS1591
        CustodyCrypto,
        #pragma warning restore CS1591
        [EnumMember(Value = "custodyFiat")]
        #pragma warning disable CS1591
        CustodyFiat,
        #pragma warning restore CS1591
        [EnumMember(Value = "custodyStablecoin")]
        #pragma warning disable CS1591
        CustodyStablecoin,
        #pragma warning restore CS1591
        [EnumMember(Value = "tradeCrypto")]
        #pragma warning disable CS1591
        TradeCrypto,
        #pragma warning restore CS1591
        [EnumMember(Value = "tradeStablecoin")]
        #pragma warning disable CS1591
        TradeStablecoin,
        #pragma warning restore CS1591
        [EnumMember(Value = "transferCrypto")]
        #pragma warning disable CS1591
        TransferCrypto,
        #pragma warning restore CS1591
        [EnumMember(Value = "transferFiat")]
        #pragma warning disable CS1591
        TransferFiat,
        #pragma warning restore CS1591
        [EnumMember(Value = "transferStablecoin")]
        #pragma warning disable CS1591
        TransferStablecoin,
        #pragma warning restore CS1591
    }
}
