// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Coinbase.OpenApiClients.Cdp.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class CreateOnrampSessionRequest : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The IP address of the end user requesting the onramp transaction.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ClientIp { get; set; }
#nullable restore
#else
        public string ClientIp { get; set; }
#endif
        /// <summary>The ISO 3166-1 two letter country code (e.g. US).</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Country { get; set; }
#nullable restore
#else
        public string Country { get; set; }
#endif
        /// <summary>A blockchain address. Format varies by network (e.g., 0x-prefixed for EVM, base58 for Solana).</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? DestinationAddress { get; set; }
#nullable restore
#else
        public string DestinationAddress { get; set; }
#endif
        /// <summary>The name of the crypto network the purchased currency will be sent on.Use the [Onramp Buy Options API](https://docs.cdp.coinbase.com/api-reference/rest-api/onramp-offramp/get-buy-options) to discover the supported networks for your user&apos;s location.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? DestinationNetwork { get; set; }
#nullable restore
#else
        public string DestinationNetwork { get; set; }
#endif
        /// <summary>A unique string that represents the user in your app. This can be used to link individual transactions together so you can retrieve the transaction history for your users. Prefix this string with “sandbox-”  (e.g. &quot;sandbox-user-1234&quot;) to perform a sandbox transaction which will allow you to test your integration  without any real transfer of funds.This value can be used with with [Onramp User Transactions API](https://docs.cdp.coinbase.com/api-reference/rest-api/onramp-offramp/get-onramp-transactions-by-id) to retrieve all transactions created by the user.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? PartnerUserRef { get; set; }
#nullable restore
#else
        public string PartnerUserRef { get; set; }
#endif
        /// <summary>A string representing the amount of fiat the user wishes to pay in exchange for crypto. When using this parameter, the returned quote will be inclusive of fees i.e. the user  will pay this exact amount of the payment currency.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? PaymentAmount { get; set; }
#nullable restore
#else
        public string PaymentAmount { get; set; }
#endif
        /// <summary>The fiat currency to be converted to crypto.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? PaymentCurrency { get; set; }
#nullable restore
#else
        public string PaymentCurrency { get; set; }
#endif
        /// <summary>The type of payment method used to generate the onramp quote.</summary>
        public global::Soenneker.Coinbase.OpenApiClients.Cdp.Models.OnrampQuotePaymentMethodTypeId? PaymentMethod { get; set; }
        /// <summary>A string representing the amount of crypto the user wishes to purchase. When using  this parameter, the returned quote will be exclusive of fees i.e. the user will  receive this exact amount of the purchase currency.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? PurchaseAmount { get; set; }
#nullable restore
#else
        public string PurchaseAmount { get; set; }
#endif
        /// <summary>The ticker (e.g. `BTC`, `USDC`, `SOL`) or the Coinbase UUID (e.g. `d85dce9b-5b73-5c3c-8978-522ce1d1c1b4`)  of the crypto asset to be purchased.Use the [Onramp Buy Options API](https://docs.cdp.coinbase.com/api-reference/rest-api/onramp-offramp/get-buy-options) to discover the supported purchase currencies for your user&apos;s location.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? PurchaseCurrency { get; set; }
#nullable restore
#else
        public string PurchaseCurrency { get; set; }
#endif
        /// <summary>A valid URI.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? RedirectUrl { get; set; }
#nullable restore
#else
        public string RedirectUrl { get; set; }
#endif
        /// <summary>The ISO 3166-2 two letter state code (e.g. NY). Only required for US.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Subdivision { get; set; }
#nullable restore
#else
        public string Subdivision { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Coinbase.OpenApiClients.Cdp.Models.CreateOnrampSessionRequest"/> and sets the default values.
        /// </summary>
        public CreateOnrampSessionRequest()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Coinbase.OpenApiClients.Cdp.Models.CreateOnrampSessionRequest"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Coinbase.OpenApiClients.Cdp.Models.CreateOnrampSessionRequest CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Coinbase.OpenApiClients.Cdp.Models.CreateOnrampSessionRequest();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "clientIp", n => { ClientIp = n.GetStringValue(); } },
                { "country", n => { Country = n.GetStringValue(); } },
                { "destinationAddress", n => { DestinationAddress = n.GetStringValue(); } },
                { "destinationNetwork", n => { DestinationNetwork = n.GetStringValue(); } },
                { "partnerUserRef", n => { PartnerUserRef = n.GetStringValue(); } },
                { "paymentAmount", n => { PaymentAmount = n.GetStringValue(); } },
                { "paymentCurrency", n => { PaymentCurrency = n.GetStringValue(); } },
                { "paymentMethod", n => { PaymentMethod = n.GetEnumValue<global::Soenneker.Coinbase.OpenApiClients.Cdp.Models.OnrampQuotePaymentMethodTypeId>(); } },
                { "purchaseAmount", n => { PurchaseAmount = n.GetStringValue(); } },
                { "purchaseCurrency", n => { PurchaseCurrency = n.GetStringValue(); } },
                { "redirectUrl", n => { RedirectUrl = n.GetStringValue(); } },
                { "subdivision", n => { Subdivision = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("clientIp", ClientIp);
            writer.WriteStringValue("country", Country);
            writer.WriteStringValue("destinationAddress", DestinationAddress);
            writer.WriteStringValue("destinationNetwork", DestinationNetwork);
            writer.WriteStringValue("partnerUserRef", PartnerUserRef);
            writer.WriteStringValue("paymentAmount", PaymentAmount);
            writer.WriteStringValue("paymentCurrency", PaymentCurrency);
            writer.WriteEnumValue<global::Soenneker.Coinbase.OpenApiClients.Cdp.Models.OnrampQuotePaymentMethodTypeId>("paymentMethod", PaymentMethod);
            writer.WriteStringValue("purchaseAmount", PurchaseAmount);
            writer.WriteStringValue("purchaseCurrency", PurchaseCurrency);
            writer.WriteStringValue("redirectUrl", RedirectUrl);
            writer.WriteStringValue("subdivision", Subdivision);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
