// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Coinbase.OpenApiClients.Cdp.Models
{
    /// <summary>
    /// A request to create a new payment session.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class CreatePaymentSessionRequest : IAdditionalDataHolder, IParsable
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>A decimal representation of the payment amount, denominated in `asset`.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Amount { get; set; }
#nullable restore
#else
        public string Amount { get; set; }
#endif
        /// <summary>The symbol of the asset (e.g., eth, usd, usdc, usdt).</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Asset { get; set; }
#nullable restore
#else
        public string Asset { get; set; }
#endif
        /// <summary>When true, a capture is automatically created after a successful authorization. When false or omitted, the merchant must create captures manually via the captures endpoint.</summary>
        public bool? AutoCapture { get; set; }
        /// <summary>Compliance context for this payment session. Carries buyer information required by some entity configurations to meet regulatory requirements.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Coinbase.OpenApiClients.Cdp.Models.CreatePaymentSessionRequestCompliance? Compliance { get; set; }
#nullable restore
#else
        public global::Soenneker.Coinbase.OpenApiClients.Cdp.Models.CreatePaymentSessionRequestCompliance Compliance { get; set; }
#endif
        /// <summary>Merchant-provided display data shown to the payer during checkout. All fields are informational only — stored and returned as-is, with no effect on payment processing, settlement, or validation.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Coinbase.OpenApiClients.Cdp.Models.CustomerDisplay? CustomerDisplay { get; set; }
#nullable restore
#else
        public global::Soenneker.Coinbase.OpenApiClients.Cdp.Models.CustomerDisplay CustomerDisplay { get; set; }
#endif
        /// <summary>Deadlines for each stage of the payment session lifecycle. All fields are optional; when omitted from a create request, the following defaults apply: `authorizationExpiresAt` = now + 1 day, `captureExpiresAt` = now + 7 days, `refundExpiresAt` = now + 30 days.Expiries must satisfy `authorizationExpiresAt` ≤ `captureExpiresAt` ≤ `refundExpiresAt`. The API returns a 400 error if this constraint is violated.Each deadline acts as a guard — after it passes, the corresponding action is rejected, but the session remains in its current status. No automatic state transitions occur; the merchant must take explicit action (e.g., cancel or void) to move the session to a terminal state.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Coinbase.OpenApiClients.Cdp.Models.PaymentExpiries? Expiries { get; set; }
#nullable restore
#else
        public global::Soenneker.Coinbase.OpenApiClients.Cdp.Models.PaymentExpiries Expiries { get; set; }
#endif
        /// <summary>A merchant-provided internal identifier for this payment session, from the merchant&apos;s own system—not visible to the payer. It must not contain personally identifiable information (PII) or payment credentials.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ExternalReferenceId { get; set; }
#nullable restore
#else
        public string ExternalReferenceId { get; set; }
#endif
        /// <summary>Optional metadata as key-value pairs. Use this to store additional structured information on a resource, such as customer IDs, order references, or any application-specific data. Up to 10 key/value pairs may be provided. Keys and values are both strings. Keys must be ≤ 40 characters; values must be ≤ 500 characters.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Coinbase.OpenApiClients.Cdp.Models.CreatePaymentSessionRequestMetadata? Metadata { get; set; }
#nullable restore
#else
        public global::Soenneker.Coinbase.OpenApiClients.Cdp.Models.CreatePaymentSessionRequestMetadata Metadata { get; set; }
#endif
        /// <summary>Redirect URLs used to direct the payer after a web-based payment flow completes or fails.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Coinbase.OpenApiClients.Cdp.Models.PaymentRedirect? Redirect { get; set; }
#nullable restore
#else
        public global::Soenneker.Coinbase.OpenApiClients.Cdp.Models.PaymentRedirect Redirect { get; set; }
#endif
        /// <summary>The target of the payment session.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Coinbase.OpenApiClients.Cdp.Models.CreatePaymentSessionRequestTarget? Target { get; set; }
#nullable restore
#else
        public global::Soenneker.Coinbase.OpenApiClients.Cdp.Models.CreatePaymentSessionRequestTarget Target { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Coinbase.OpenApiClients.Cdp.Models.CreatePaymentSessionRequest"/> and sets the default values.
        /// </summary>
        public CreatePaymentSessionRequest()
        {
            AdditionalData = new Dictionary<string, object>();
            AutoCapture = false;
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Coinbase.OpenApiClients.Cdp.Models.CreatePaymentSessionRequest"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Coinbase.OpenApiClients.Cdp.Models.CreatePaymentSessionRequest CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Coinbase.OpenApiClients.Cdp.Models.CreatePaymentSessionRequest();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "amount", n => { Amount = n.GetStringValue(); } },
                { "asset", n => { Asset = n.GetStringValue(); } },
                { "autoCapture", n => { AutoCapture = n.GetBoolValue(); } },
                { "compliance", n => { Compliance = n.GetObjectValue<global::Soenneker.Coinbase.OpenApiClients.Cdp.Models.CreatePaymentSessionRequestCompliance>(global::Soenneker.Coinbase.OpenApiClients.Cdp.Models.CreatePaymentSessionRequestCompliance.CreateFromDiscriminatorValue); } },
                { "customerDisplay", n => { CustomerDisplay = n.GetObjectValue<global::Soenneker.Coinbase.OpenApiClients.Cdp.Models.CustomerDisplay>(global::Soenneker.Coinbase.OpenApiClients.Cdp.Models.CustomerDisplay.CreateFromDiscriminatorValue); } },
                { "expiries", n => { Expiries = n.GetObjectValue<global::Soenneker.Coinbase.OpenApiClients.Cdp.Models.PaymentExpiries>(global::Soenneker.Coinbase.OpenApiClients.Cdp.Models.PaymentExpiries.CreateFromDiscriminatorValue); } },
                { "externalReferenceId", n => { ExternalReferenceId = n.GetStringValue(); } },
                { "metadata", n => { Metadata = n.GetObjectValue<global::Soenneker.Coinbase.OpenApiClients.Cdp.Models.CreatePaymentSessionRequestMetadata>(global::Soenneker.Coinbase.OpenApiClients.Cdp.Models.CreatePaymentSessionRequestMetadata.CreateFromDiscriminatorValue); } },
                { "redirect", n => { Redirect = n.GetObjectValue<global::Soenneker.Coinbase.OpenApiClients.Cdp.Models.PaymentRedirect>(global::Soenneker.Coinbase.OpenApiClients.Cdp.Models.PaymentRedirect.CreateFromDiscriminatorValue); } },
                { "target", n => { Target = n.GetObjectValue<global::Soenneker.Coinbase.OpenApiClients.Cdp.Models.CreatePaymentSessionRequestTarget>(global::Soenneker.Coinbase.OpenApiClients.Cdp.Models.CreatePaymentSessionRequestTarget.CreateFromDiscriminatorValue); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("amount", Amount);
            writer.WriteStringValue("asset", Asset);
            writer.WriteBoolValue("autoCapture", AutoCapture);
            writer.WriteObjectValue<global::Soenneker.Coinbase.OpenApiClients.Cdp.Models.CreatePaymentSessionRequestCompliance>("compliance", Compliance);
            writer.WriteObjectValue<global::Soenneker.Coinbase.OpenApiClients.Cdp.Models.CustomerDisplay>("customerDisplay", CustomerDisplay);
            writer.WriteObjectValue<global::Soenneker.Coinbase.OpenApiClients.Cdp.Models.PaymentExpiries>("expiries", Expiries);
            writer.WriteStringValue("externalReferenceId", ExternalReferenceId);
            writer.WriteObjectValue<global::Soenneker.Coinbase.OpenApiClients.Cdp.Models.CreatePaymentSessionRequestMetadata>("metadata", Metadata);
            writer.WriteObjectValue<global::Soenneker.Coinbase.OpenApiClients.Cdp.Models.PaymentRedirect>("redirect", Redirect);
            writer.WriteObjectValue<global::Soenneker.Coinbase.OpenApiClients.Cdp.Models.CreatePaymentSessionRequestTarget>("target", Target);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
