// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Coinbase.OpenApiClients.Cdp.Models
{
    /// <summary>
    /// A request to create a new mandate. The merchant is inferred from the API key. The mandate is returned in `created` status with no source. Attach a source next by approving the mandate, using **Get wallet approval options** then **Approve a mandate with a wallet**, which returns a `pending` approval; the mandate becomes `approval_succeeded` once that approval succeeds. The mandate is denominated in `asset`, fixed at creation. `policy` is optional. Omit it or send `{}` to default to a Coinbase-configured monthly max. The response includes the resolved `policy`. If you set `maxPerPeriod`, include both `amount` and `period`.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class CreateMandateRequest : IAdditionalDataHolder, IParsable
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>Optional merchant URLs used by the hosted mandate approval flow. The approval page redirects to `successUrl` when approval succeeds, or `failureUrl` when it fails. Omit to keep the customer on the Coinbase-hosted experience.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Coinbase.OpenApiClients.Cdp.Models.CreateMandateRequestApprovalRedirect? ApprovalRedirect { get; set; }
#nullable restore
#else
        public global::Soenneker.Coinbase.OpenApiClients.Cdp.Models.CreateMandateRequestApprovalRedirect ApprovalRedirect { get; set; }
#endif
        /// <summary>The symbol of the asset (e.g., eth, usd, usdc, usdt).</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Asset { get; set; }
#nullable restore
#else
        public string Asset { get; set; }
#endif
        /// <summary>Merchant-provided display data shown to the customer on the hosted mandate pages. All fields are informational only. They are stored and returned as-is and do not affect mandate approval, authorization, or policy enforcement.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Coinbase.OpenApiClients.Cdp.Models.MandateCustomerDisplay? CustomerDisplay { get; set; }
#nullable restore
#else
        public global::Soenneker.Coinbase.OpenApiClients.Cdp.Models.MandateCustomerDisplay CustomerDisplay { get; set; }
#endif
        /// <summary>The UTC ISO 8601 timestamp after which this mandate can no longer be authorized against. Omit for a mandate with no expiry.</summary>
        public DateTimeOffset? ExpiresAt { get; set; }
        /// <summary>Optional metadata as key-value pairs. Use this to store additional structured information on a resource, such as customer IDs, order references, or any application-specific data. Up to 10 key/value pairs may be provided. Keys and values are both strings. Keys must be ≤ 40 characters; values must be ≤ 500 characters.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Coinbase.OpenApiClients.Cdp.Models.CreateMandateRequestMetadata? Metadata { get; set; }
#nullable restore
#else
        public global::Soenneker.Coinbase.OpenApiClients.Cdp.Models.CreateMandateRequestMetadata Metadata { get; set; }
#endif
        /// <summary>Optional. Omit or send `{}` to default to a Coinbase-configured monthly max. If you set `maxPerPeriod`, include both `amount` and `period`.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Coinbase.OpenApiClients.Cdp.Models.CreateMandateRequestPolicy? Policy { get; set; }
#nullable restore
#else
        public global::Soenneker.Coinbase.OpenApiClients.Cdp.Models.CreateMandateRequestPolicy Policy { get; set; }
#endif
        /// <summary>Optional merchant URLs used by the hosted mandate revocation flow. The revocation page redirects to `successUrl` when revocation succeeds, or `failureUrl` when it fails. Omit to keep the customer on the Coinbase-hosted experience.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Coinbase.OpenApiClients.Cdp.Models.CreateMandateRequestRevocationRedirect? RevocationRedirect { get; set; }
#nullable restore
#else
        public global::Soenneker.Coinbase.OpenApiClients.Cdp.Models.CreateMandateRequestRevocationRedirect RevocationRedirect { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Coinbase.OpenApiClients.Cdp.Models.CreateMandateRequest"/> and sets the default values.
        /// </summary>
        public CreateMandateRequest()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Coinbase.OpenApiClients.Cdp.Models.CreateMandateRequest"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Coinbase.OpenApiClients.Cdp.Models.CreateMandateRequest CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Coinbase.OpenApiClients.Cdp.Models.CreateMandateRequest();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "approvalRedirect", n => { ApprovalRedirect = n.GetObjectValue<global::Soenneker.Coinbase.OpenApiClients.Cdp.Models.CreateMandateRequestApprovalRedirect>(global::Soenneker.Coinbase.OpenApiClients.Cdp.Models.CreateMandateRequestApprovalRedirect.CreateFromDiscriminatorValue); } },
                { "asset", n => { Asset = n.GetStringValue(); } },
                { "customerDisplay", n => { CustomerDisplay = n.GetObjectValue<global::Soenneker.Coinbase.OpenApiClients.Cdp.Models.MandateCustomerDisplay>(global::Soenneker.Coinbase.OpenApiClients.Cdp.Models.MandateCustomerDisplay.CreateFromDiscriminatorValue); } },
                { "expiresAt", n => { ExpiresAt = n.GetDateTimeOffsetValue(); } },
                { "metadata", n => { Metadata = n.GetObjectValue<global::Soenneker.Coinbase.OpenApiClients.Cdp.Models.CreateMandateRequestMetadata>(global::Soenneker.Coinbase.OpenApiClients.Cdp.Models.CreateMandateRequestMetadata.CreateFromDiscriminatorValue); } },
                { "policy", n => { Policy = n.GetObjectValue<global::Soenneker.Coinbase.OpenApiClients.Cdp.Models.CreateMandateRequestPolicy>(global::Soenneker.Coinbase.OpenApiClients.Cdp.Models.CreateMandateRequestPolicy.CreateFromDiscriminatorValue); } },
                { "revocationRedirect", n => { RevocationRedirect = n.GetObjectValue<global::Soenneker.Coinbase.OpenApiClients.Cdp.Models.CreateMandateRequestRevocationRedirect>(global::Soenneker.Coinbase.OpenApiClients.Cdp.Models.CreateMandateRequestRevocationRedirect.CreateFromDiscriminatorValue); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteObjectValue<global::Soenneker.Coinbase.OpenApiClients.Cdp.Models.CreateMandateRequestApprovalRedirect>("approvalRedirect", ApprovalRedirect);
            writer.WriteStringValue("asset", Asset);
            writer.WriteObjectValue<global::Soenneker.Coinbase.OpenApiClients.Cdp.Models.MandateCustomerDisplay>("customerDisplay", CustomerDisplay);
            writer.WriteDateTimeOffsetValue("expiresAt", ExpiresAt);
            writer.WriteObjectValue<global::Soenneker.Coinbase.OpenApiClients.Cdp.Models.CreateMandateRequestMetadata>("metadata", Metadata);
            writer.WriteObjectValue<global::Soenneker.Coinbase.OpenApiClients.Cdp.Models.CreateMandateRequestPolicy>("policy", Policy);
            writer.WriteObjectValue<global::Soenneker.Coinbase.OpenApiClients.Cdp.Models.CreateMandateRequestRevocationRedirect>("revocationRedirect", RevocationRedirect);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
