// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Coinbase.OpenApiClients.Cdp.Models
{
    /// <summary>
    /// Information about an Individual customer. Not all fields are requiredfor all customers; the requirements depend on which capabilities arerequested. Submit only fields that are required by the capabilitiesthat have been requested.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class CustomerWriteBaseIndividual : IAdditionalDataHolder, IParsable
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>Primary residential address. Only US addresses are currentlysupported. Non-US `countryCode` values are rejected with a 400.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Coinbase.OpenApiClients.Cdp.Models.IndividualInputAddress? Address { get; set; }
#nullable restore
#else
        public global::Soenneker.Coinbase.OpenApiClients.Cdp.Models.IndividualInputAddress Address { get; set; }
#endif
        /// <summary>An ISO 3166-1 alpha-2 country code.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Citizenship { get; set; }
#nullable restore
#else
        public string Citizenship { get; set; }
#endif
        /// <summary>Date of birth.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Coinbase.OpenApiClients.Cdp.Models.IndividualInputDateOfBirth? DateOfBirth { get; set; }
#nullable restore
#else
        public global::Soenneker.Coinbase.OpenApiClients.Cdp.Models.IndividualInputDateOfBirth DateOfBirth { get; set; }
#endif
        /// <summary>An email address. Maximum length 254 characters per [RFC 5321](https://www.rfc-editor.org/rfc/rfc5321).</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Email { get; set; }
#nullable restore
#else
        public string Email { get; set; }
#endif
        /// <summary>Current employment status.</summary>
        public global::Soenneker.Coinbase.OpenApiClients.Cdp.Models.CustomerWriteBaseIndividualEmploymentStatus? EmploymentStatus { get; set; }
        /// <summary>Expected annual volume of activity on the account, expressed as adollar range. Use the dollar-honest ids below:- `under_1k`: $0 – $1,000- `1k_to_10k`: $1,000 – $10,000- `10k_to_100k`: $10,000 – $100,000- `100k_to_250k`: $100,000 – $250,000- `250k_to_750k`: $250,000 – $750,000- `750k_to_1_5m`: $750,000 – $1.5M- `1_5m_plus`: $1.5M+</summary>
        public global::Soenneker.Coinbase.OpenApiClients.Cdp.Models.CustomerWriteBaseIndividualExpectedVolume? ExpectedVolume { get; set; }
        /// <summary>First name (given name).</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? FirstName { get; set; }
#nullable restore
#else
        public string FirstName { get; set; }
#endif
        /// <summary>Full Social Security Number (US only).</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? FullSsn { get; set; }
#nullable restore
#else
        public string FullSsn { get; set; }
#endif
        /// <summary>Last name (family name/surname).</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? LastName { get; set; }
#nullable restore
#else
        public string LastName { get; set; }
#endif
        /// <summary>Industry or occupation.</summary>
        public global::Soenneker.Coinbase.OpenApiClients.Cdp.Models.CustomerWriteBaseIndividualOccupation? Occupation { get; set; }
        /// <summary>A phone number in [E.164](https://en.wikipedia.org/wiki/E.164) format.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? PhoneNumber { get; set; }
#nullable restore
#else
        public string PhoneNumber { get; set; }
#endif
        /// <summary>Primary purpose for using Coinbase services.</summary>
        public global::Soenneker.Coinbase.OpenApiClients.Cdp.Models.CustomerWriteBaseIndividualPurposeOfAccount? PurposeOfAccount { get; set; }
        /// <summary>Primary source of funds for the account.</summary>
        public global::Soenneker.Coinbase.OpenApiClients.Cdp.Models.CustomerWriteBaseIndividualSourceOfFunds? SourceOfFunds { get; set; }
        /// <summary>Last 4 digits of the Social Security Number (US only).Used for identity verification.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? SsnLast4 { get; set; }
#nullable restore
#else
        public string SsnLast4 { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Coinbase.OpenApiClients.Cdp.Models.CustomerWriteBaseIndividual"/> and sets the default values.
        /// </summary>
        public CustomerWriteBaseIndividual()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Coinbase.OpenApiClients.Cdp.Models.CustomerWriteBaseIndividual"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Coinbase.OpenApiClients.Cdp.Models.CustomerWriteBaseIndividual CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Coinbase.OpenApiClients.Cdp.Models.CustomerWriteBaseIndividual();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "address", n => { Address = n.GetObjectValue<global::Soenneker.Coinbase.OpenApiClients.Cdp.Models.IndividualInputAddress>(global::Soenneker.Coinbase.OpenApiClients.Cdp.Models.IndividualInputAddress.CreateFromDiscriminatorValue); } },
                { "citizenship", n => { Citizenship = n.GetStringValue(); } },
                { "dateOfBirth", n => { DateOfBirth = n.GetObjectValue<global::Soenneker.Coinbase.OpenApiClients.Cdp.Models.IndividualInputDateOfBirth>(global::Soenneker.Coinbase.OpenApiClients.Cdp.Models.IndividualInputDateOfBirth.CreateFromDiscriminatorValue); } },
                { "email", n => { Email = n.GetStringValue(); } },
                { "employmentStatus", n => { EmploymentStatus = n.GetEnumValue<global::Soenneker.Coinbase.OpenApiClients.Cdp.Models.CustomerWriteBaseIndividualEmploymentStatus>(); } },
                { "expectedVolume", n => { ExpectedVolume = n.GetEnumValue<global::Soenneker.Coinbase.OpenApiClients.Cdp.Models.CustomerWriteBaseIndividualExpectedVolume>(); } },
                { "firstName", n => { FirstName = n.GetStringValue(); } },
                { "fullSsn", n => { FullSsn = n.GetStringValue(); } },
                { "lastName", n => { LastName = n.GetStringValue(); } },
                { "occupation", n => { Occupation = n.GetEnumValue<global::Soenneker.Coinbase.OpenApiClients.Cdp.Models.CustomerWriteBaseIndividualOccupation>(); } },
                { "phoneNumber", n => { PhoneNumber = n.GetStringValue(); } },
                { "purposeOfAccount", n => { PurposeOfAccount = n.GetEnumValue<global::Soenneker.Coinbase.OpenApiClients.Cdp.Models.CustomerWriteBaseIndividualPurposeOfAccount>(); } },
                { "sourceOfFunds", n => { SourceOfFunds = n.GetEnumValue<global::Soenneker.Coinbase.OpenApiClients.Cdp.Models.CustomerWriteBaseIndividualSourceOfFunds>(); } },
                { "ssnLast4", n => { SsnLast4 = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteObjectValue<global::Soenneker.Coinbase.OpenApiClients.Cdp.Models.IndividualInputAddress>("address", Address);
            writer.WriteStringValue("citizenship", Citizenship);
            writer.WriteObjectValue<global::Soenneker.Coinbase.OpenApiClients.Cdp.Models.IndividualInputDateOfBirth>("dateOfBirth", DateOfBirth);
            writer.WriteStringValue("email", Email);
            writer.WriteEnumValue<global::Soenneker.Coinbase.OpenApiClients.Cdp.Models.CustomerWriteBaseIndividualEmploymentStatus>("employmentStatus", EmploymentStatus);
            writer.WriteEnumValue<global::Soenneker.Coinbase.OpenApiClients.Cdp.Models.CustomerWriteBaseIndividualExpectedVolume>("expectedVolume", ExpectedVolume);
            writer.WriteStringValue("firstName", FirstName);
            writer.WriteStringValue("fullSsn", FullSsn);
            writer.WriteStringValue("lastName", LastName);
            writer.WriteEnumValue<global::Soenneker.Coinbase.OpenApiClients.Cdp.Models.CustomerWriteBaseIndividualOccupation>("occupation", Occupation);
            writer.WriteStringValue("phoneNumber", PhoneNumber);
            writer.WriteEnumValue<global::Soenneker.Coinbase.OpenApiClients.Cdp.Models.CustomerWriteBaseIndividualPurposeOfAccount>("purposeOfAccount", PurposeOfAccount);
            writer.WriteEnumValue<global::Soenneker.Coinbase.OpenApiClients.Cdp.Models.CustomerWriteBaseIndividualSourceOfFunds>("sourceOfFunds", SourceOfFunds);
            writer.WriteStringValue("ssnLast4", SsnLast4);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
