// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Coinbase.OpenApiClients.Cdp.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum DepositDestinationTypeOneOf2
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "fiat")]
        #pragma warning disable CS1591
        Fiat,
        #pragma warning restore CS1591
    }
}
