// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Coinbase.OpenApiClients.Cdp.Models
{
    /// <summary>The payload type.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum Erc20ApprovalType
    {
        [EnumMember(Value = "erc20_approval")]
        #pragma warning disable CS1591
        Erc20Approval,
        #pragma warning restore CS1591
    }
}
