// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Coinbase.OpenApiClients.Cdp.Models
{
    /// <summary>The network for the EIP-7702 delegation.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum EvmEip7702DelegationNetwork
    {
        [EnumMember(Value = "base-sepolia")]
        #pragma warning disable CS1591
        BaseSepolia,
        #pragma warning restore CS1591
        [EnumMember(Value = "base")]
        #pragma warning disable CS1591
        Base,
        #pragma warning restore CS1591
        [EnumMember(Value = "arbitrum")]
        #pragma warning disable CS1591
        Arbitrum,
        #pragma warning restore CS1591
        [EnumMember(Value = "optimism")]
        #pragma warning disable CS1591
        Optimism,
        #pragma warning restore CS1591
        [EnumMember(Value = "polygon")]
        #pragma warning disable CS1591
        Polygon,
        #pragma warning restore CS1591
        [EnumMember(Value = "ethereum")]
        #pragma warning disable CS1591
        Ethereum,
        #pragma warning restore CS1591
        [EnumMember(Value = "ethereum-sepolia")]
        #pragma warning disable CS1591
        EthereumSepolia,
        #pragma warning restore CS1591
    }
}
