// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Coinbase.OpenApiClients.Cdp.Models
{
    /// <summary>The type of webhook event.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum HealthMaintenanceCompletedEventType
    {
        [EnumMember(Value = "health.maintenance.completed")]
        #pragma warning disable CS1591
        HealthMaintenanceCompleted,
        #pragma warning restore CS1591
    }
}
