// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Coinbase.OpenApiClients.Cdp.Models
{
    /// <summary>The operational status of a service or operation. `operational`, `degraded_performance`, `partial_outage`, and `major_outage` form a severity ladder that can move up or down between adjacent levels as an organic issue develops or recovers.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum HealthStatusValue
    {
        [EnumMember(Value = "operational")]
        #pragma warning disable CS1591
        Operational,
        #pragma warning restore CS1591
        [EnumMember(Value = "degraded_performance")]
        #pragma warning disable CS1591
        DegradedPerformance,
        #pragma warning restore CS1591
        [EnumMember(Value = "partial_outage")]
        #pragma warning disable CS1591
        PartialOutage,
        #pragma warning restore CS1591
        [EnumMember(Value = "major_outage")]
        #pragma warning disable CS1591
        MajorOutage,
        #pragma warning restore CS1591
        [EnumMember(Value = "under_maintenance")]
        #pragma warning disable CS1591
        UnderMaintenance,
        #pragma warning restore CS1591
    }
}
