// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Coinbase.OpenApiClients.Cdp.Models
{
    /// <summary>The type of key being imported. Determines what type of account will be associated for the end user.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum ImportEndUser_keyType
    {
        [EnumMember(Value = "evm")]
        #pragma warning disable CS1591
        Evm,
        #pragma warning restore CS1591
        [EnumMember(Value = "solana")]
        #pragma warning disable CS1591
        Solana,
        #pragma warning restore CS1591
    }
}
