// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Coinbase.OpenApiClients.Cdp.Models
{
    /// <summary>Primary source of funds for the account.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum IndividualInputSourceOfFunds
    {
        [EnumMember(Value = "salary")]
        #pragma warning disable CS1591
        Salary,
        #pragma warning restore CS1591
        [EnumMember(Value = "employment_business_income")]
        #pragma warning disable CS1591
        EmploymentBusinessIncome,
        #pragma warning restore CS1591
        [EnumMember(Value = "investments")]
        #pragma warning disable CS1591
        Investments,
        #pragma warning restore CS1591
        [EnumMember(Value = "savings")]
        #pragma warning disable CS1591
        Savings,
        #pragma warning restore CS1591
        [EnumMember(Value = "pension")]
        #pragma warning disable CS1591
        Pension,
        #pragma warning restore CS1591
        [EnumMember(Value = "business_earnings")]
        #pragma warning disable CS1591
        BusinessEarnings,
        #pragma warning restore CS1591
        [EnumMember(Value = "crypto_assets")]
        #pragma warning disable CS1591
        CryptoAssets,
        #pragma warning restore CS1591
        [EnumMember(Value = "inheritance")]
        #pragma warning disable CS1591
        Inheritance,
        #pragma warning restore CS1591
        [EnumMember(Value = "sale_of_assets")]
        #pragma warning disable CS1591
        SaleOfAssets,
        #pragma warning restore CS1591
        [EnumMember(Value = "sale_of_company_shares_or_dividends")]
        #pragma warning disable CS1591
        SaleOfCompanySharesOrDividends,
        #pragma warning restore CS1591
        [EnumMember(Value = "sale_of_property")]
        #pragma warning disable CS1591
        SaleOfProperty,
        #pragma warning restore CS1591
        [EnumMember(Value = "sale_of_other_assets")]
        #pragma warning disable CS1591
        SaleOfOtherAssets,
        #pragma warning restore CS1591
        [EnumMember(Value = "credit_or_loan")]
        #pragma warning disable CS1591
        CreditOrLoan,
        #pragma warning restore CS1591
        [EnumMember(Value = "government_benefits_or_credits")]
        #pragma warning disable CS1591
        GovernmentBenefitsOrCredits,
        #pragma warning restore CS1591
        [EnumMember(Value = "legal_settlement")]
        #pragma warning disable CS1591
        LegalSettlement,
        #pragma warning restore CS1591
        [EnumMember(Value = "family_or_third_party")]
        #pragma warning disable CS1591
        FamilyOrThirdParty,
        #pragma warning restore CS1591
        [EnumMember(Value = "lottery_or_gambling")]
        #pragma warning disable CS1591
        LotteryOrGambling,
        #pragma warning restore CS1591
        [EnumMember(Value = "crypto_mining")]
        #pragma warning disable CS1591
        CryptoMining,
        #pragma warning restore CS1591
        [EnumMember(Value = "other")]
        #pragma warning disable CS1591
        Other,
        #pragma warning restore CS1591
    }
}
