// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Coinbase.OpenApiClients.Cdp.Models
{
    /// <summary>Expected annual volume of activity on the account, expressed as adollar range. Use the dollar-honest ids below:- `under_1k`: $0 – $1,000- `1k_to_10k`: $1,000 – $10,000- `10k_to_100k`: $10,000 – $100,000- `100k_to_250k`: $100,000 – $250,000- `250k_to_750k`: $250,000 – $750,000- `750k_to_1_5m`: $750,000 – $1.5M- `1_5m_plus`: $1.5M+</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum IndividualInputExpectedVolume
    {
        [EnumMember(Value = "under_1k")]
        #pragma warning disable CS1591
        Under1K,
        #pragma warning restore CS1591
        [EnumMember(Value = "1k_to_10k")]
        #pragma warning disable CS1591
        Value1KTo10K,
        #pragma warning restore CS1591
        [EnumMember(Value = "10k_to_100k")]
        #pragma warning disable CS1591
        Value10KTo100K,
        #pragma warning restore CS1591
        [EnumMember(Value = "100k_to_250k")]
        #pragma warning disable CS1591
        Value100KTo250K,
        #pragma warning restore CS1591
        [EnumMember(Value = "250k_to_750k")]
        #pragma warning disable CS1591
        Value250KTo750K,
        #pragma warning restore CS1591
        [EnumMember(Value = "750k_to_1_5m")]
        #pragma warning disable CS1591
        Value750KTo15M,
        #pragma warning restore CS1591
        [EnumMember(Value = "1_5m_plus")]
        #pragma warning disable CS1591
        Value15MPlus,
        #pragma warning restore CS1591
    }
}
