// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Coinbase.OpenApiClients.Cdp.Models
{
    /// <summary>
    /// The approval attempt this event concerns. Present only on the approval events (`acceptance.mandate.approval_initiated`, `acceptance.mandate.approval_succeeded`, and `acceptance.mandate.approval_failed`); absent on all other events. A `failed` approval carries an `error`.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class MandateEventDataApproval : IAdditionalDataHolder, IParsable
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The ID of an approval, a UUID prefixed by `approval_`.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ApprovalId { get; set; }
#nullable restore
#else
        public string ApprovalId { get; set; }
#endif
        /// <summary>The UTC ISO 8601 timestamp at which the approval was created.</summary>
        public DateTimeOffset? CreatedAt { get; set; }
        /// <summary>Details of why the approval failed. Only present when `status` is `failed`.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Coinbase.OpenApiClients.Cdp.Models.ApprovalError? Error { get; set; }
#nullable restore
#else
        public global::Soenneker.Coinbase.OpenApiClients.Cdp.Models.ApprovalError Error { get; set; }
#endif
        /// <summary>Optional metadata as key-value pairs. Use this to store additional structured information on a resource, such as customer IDs, order references, or any application-specific data. Up to 10 key/value pairs may be provided. Keys and values are both strings. Keys must be ≤ 40 characters; values must be ≤ 500 characters.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Coinbase.OpenApiClients.Cdp.Models.MandateEventDataApprovalMetadata? Metadata { get; set; }
#nullable restore
#else
        public global::Soenneker.Coinbase.OpenApiClients.Cdp.Models.MandateEventDataApprovalMetadata Metadata { get; set; }
#endif
        /// <summary>Network transactions that grant the spending allowance on-chain. Empty until the approval has been submitted to the network.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Coinbase.OpenApiClients.Cdp.Models.OnchainTransaction>? OnchainTransactions { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Coinbase.OpenApiClients.Cdp.Models.OnchainTransaction> OnchainTransactions { get; set; }
#endif
        /// <summary>The funding source this approval binds to the mandate. Present once the source has been determined from the customer&apos;s submission.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Coinbase.OpenApiClients.Cdp.Models.ApprovalSource? Source { get; set; }
#nullable restore
#else
        public global::Soenneker.Coinbase.OpenApiClients.Cdp.Models.ApprovalSource Source { get; set; }
#endif
        /// <summary>The current status of the approval attempt.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Coinbase.OpenApiClients.Cdp.Models.ApprovalStatusComposed? Status { get; set; }
#nullable restore
#else
        public global::Soenneker.Coinbase.OpenApiClients.Cdp.Models.ApprovalStatusComposed Status { get; set; }
#endif
        /// <summary>The UTC ISO 8601 timestamp at which the approval was last updated.</summary>
        public DateTimeOffset? UpdatedAt { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Coinbase.OpenApiClients.Cdp.Models.MandateEventDataApproval"/> and sets the default values.
        /// </summary>
        public MandateEventDataApproval()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Coinbase.OpenApiClients.Cdp.Models.MandateEventDataApproval"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Coinbase.OpenApiClients.Cdp.Models.MandateEventDataApproval CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Coinbase.OpenApiClients.Cdp.Models.MandateEventDataApproval();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "approvalId", n => { ApprovalId = n.GetStringValue(); } },
                { "createdAt", n => { CreatedAt = n.GetDateTimeOffsetValue(); } },
                { "error", n => { Error = n.GetObjectValue<global::Soenneker.Coinbase.OpenApiClients.Cdp.Models.ApprovalError>(global::Soenneker.Coinbase.OpenApiClients.Cdp.Models.ApprovalError.CreateFromDiscriminatorValue); } },
                { "metadata", n => { Metadata = n.GetObjectValue<global::Soenneker.Coinbase.OpenApiClients.Cdp.Models.MandateEventDataApprovalMetadata>(global::Soenneker.Coinbase.OpenApiClients.Cdp.Models.MandateEventDataApprovalMetadata.CreateFromDiscriminatorValue); } },
                { "onchainTransactions", n => { OnchainTransactions = n.GetCollectionOfObjectValues<global::Soenneker.Coinbase.OpenApiClients.Cdp.Models.OnchainTransaction>(global::Soenneker.Coinbase.OpenApiClients.Cdp.Models.OnchainTransaction.CreateFromDiscriminatorValue)?.AsList(); } },
                { "source", n => { Source = n.GetObjectValue<global::Soenneker.Coinbase.OpenApiClients.Cdp.Models.ApprovalSource>(global::Soenneker.Coinbase.OpenApiClients.Cdp.Models.ApprovalSource.CreateFromDiscriminatorValue); } },
                { "status", n => { Status = n.GetObjectValue<global::Soenneker.Coinbase.OpenApiClients.Cdp.Models.ApprovalStatusComposed>(global::Soenneker.Coinbase.OpenApiClients.Cdp.Models.ApprovalStatusComposed.CreateFromDiscriminatorValue); } },
                { "updatedAt", n => { UpdatedAt = n.GetDateTimeOffsetValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("approvalId", ApprovalId);
            writer.WriteDateTimeOffsetValue("createdAt", CreatedAt);
            writer.WriteObjectValue<global::Soenneker.Coinbase.OpenApiClients.Cdp.Models.ApprovalError>("error", Error);
            writer.WriteObjectValue<global::Soenneker.Coinbase.OpenApiClients.Cdp.Models.MandateEventDataApprovalMetadata>("metadata", Metadata);
            writer.WriteCollectionOfObjectValues<global::Soenneker.Coinbase.OpenApiClients.Cdp.Models.OnchainTransaction>("onchainTransactions", OnchainTransactions);
            writer.WriteObjectValue<global::Soenneker.Coinbase.OpenApiClients.Cdp.Models.ApprovalSource>("source", Source);
            writer.WriteObjectValue<global::Soenneker.Coinbase.OpenApiClients.Cdp.Models.ApprovalStatusComposed>("status", Status);
            writer.WriteDateTimeOffsetValue("updatedAt", UpdatedAt);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
