// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Coinbase.OpenApiClients.Cdp.Models
{
    /// <summary>
    /// The `data` payload for every mandate webhook event. Always contains the full `mandate`. Action events also carry the relevant sub-resource: `approval` on the three `approval_*` events, `revocation` on the three `revocation_*` events. The `created` and `canceled` events carry only the `mandate`.`mandate.status` reflects only the latest action. Read `mandate.canceledAt` and `mandate.revokedAt` to know what has durably happened: the on-chain spending allowance is gone precisely when `revokedAt` is set, and canceling alone does not remove it.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class MandateEventData : IAdditionalDataHolder, IParsable
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The approval attempt this event concerns. Present only on the approval events (`acceptance.mandate.approval_initiated`, `acceptance.mandate.approval_succeeded`, and `acceptance.mandate.approval_failed`); absent on all other events. A `failed` approval carries an `error`.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Coinbase.OpenApiClients.Cdp.Models.MandateEventDataApproval? Approval { get; set; }
#nullable restore
#else
        public global::Soenneker.Coinbase.OpenApiClients.Cdp.Models.MandateEventDataApproval Approval { get; set; }
#endif
        /// <summary>A durable, revocable standing authorization to debit a funding `source` without the customer present each time, within its `policy` caps. Payment sessions draw against it by referencing its `mandateId`.`source` is set once an approval succeeds. `status` reflects the most recent action; the `approvedAt`, `canceledAt`, and `revokedAt` timestamps are the durable record of what has happened. Ending one mandate does not affect other mandates on the same `source`.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Coinbase.OpenApiClients.Cdp.Models.Mandate? Mandate { get; set; }
#nullable restore
#else
        public global::Soenneker.Coinbase.OpenApiClients.Cdp.Models.Mandate Mandate { get; set; }
#endif
        /// <summary>The wallet revocation this event concerns. Present only on revocation events (`revocation_initiated`, `revocation_succeeded`, `revocation_failed`); absent on all others. A `failed` revocation carries an `error`.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Coinbase.OpenApiClients.Cdp.Models.MandateEventDataRevocation? Revocation { get; set; }
#nullable restore
#else
        public global::Soenneker.Coinbase.OpenApiClients.Cdp.Models.MandateEventDataRevocation Revocation { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Coinbase.OpenApiClients.Cdp.Models.MandateEventData"/> and sets the default values.
        /// </summary>
        public MandateEventData()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Coinbase.OpenApiClients.Cdp.Models.MandateEventData"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Coinbase.OpenApiClients.Cdp.Models.MandateEventData CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Coinbase.OpenApiClients.Cdp.Models.MandateEventData();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "approval", n => { Approval = n.GetObjectValue<global::Soenneker.Coinbase.OpenApiClients.Cdp.Models.MandateEventDataApproval>(global::Soenneker.Coinbase.OpenApiClients.Cdp.Models.MandateEventDataApproval.CreateFromDiscriminatorValue); } },
                { "mandate", n => { Mandate = n.GetObjectValue<global::Soenneker.Coinbase.OpenApiClients.Cdp.Models.Mandate>(global::Soenneker.Coinbase.OpenApiClients.Cdp.Models.Mandate.CreateFromDiscriminatorValue); } },
                { "revocation", n => { Revocation = n.GetObjectValue<global::Soenneker.Coinbase.OpenApiClients.Cdp.Models.MandateEventDataRevocation>(global::Soenneker.Coinbase.OpenApiClients.Cdp.Models.MandateEventDataRevocation.CreateFromDiscriminatorValue); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteObjectValue<global::Soenneker.Coinbase.OpenApiClients.Cdp.Models.MandateEventDataApproval>("approval", Approval);
            writer.WriteObjectValue<global::Soenneker.Coinbase.OpenApiClients.Cdp.Models.Mandate>("mandate", Mandate);
            writer.WriteObjectValue<global::Soenneker.Coinbase.OpenApiClients.Cdp.Models.MandateEventDataRevocation>("revocation", Revocation);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
