// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Coinbase.OpenApiClients.Cdp.Models
{
    /// <summary>
    /// Morpho Blue&apos;s immutable onchain market parameters that uniquely define a borrow product.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class MorphoBlueMarketParams : IAdditionalDataHolder, IParsable
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The token posted as collateral in the product.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Coinbase.OpenApiClients.Cdp.Models.BorrowProductToken? CollateralToken { get; set; }
#nullable restore
#else
        public global::Soenneker.Coinbase.OpenApiClients.Cdp.Models.BorrowProductToken CollateralToken { get; set; }
#endif
        /// <summary>The contract address of the interest rate model that governs the product&apos;s borrow rate.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? InterestRateModelAddress { get; set; }
#nullable restore
#else
        public string InterestRateModelAddress { get; set; }
#endif
        /// <summary>The liquidation loan-to-value of the product, expressed in basis points. For example, `9150` represents an LLTV of 91.5%.</summary>
        public int? LltvBps { get; set; }
        /// <summary>The token that is borrowed in the product.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Coinbase.OpenApiClients.Cdp.Models.BorrowProductToken? LoanToken { get; set; }
#nullable restore
#else
        public global::Soenneker.Coinbase.OpenApiClients.Cdp.Models.BorrowProductToken LoanToken { get; set; }
#endif
        /// <summary>The Morpho Blue native bytes32 market ID that uniquely identifies  the underlying market onchain.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? OnchainMarketId { get; set; }
#nullable restore
#else
        public string OnchainMarketId { get; set; }
#endif
        /// <summary>The contract address of the oracle used to price the collateral token against the loan token.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? OracleAddress { get; set; }
#nullable restore
#else
        public string OracleAddress { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Coinbase.OpenApiClients.Cdp.Models.MorphoBlueMarketParams"/> and sets the default values.
        /// </summary>
        public MorphoBlueMarketParams()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Coinbase.OpenApiClients.Cdp.Models.MorphoBlueMarketParams"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Coinbase.OpenApiClients.Cdp.Models.MorphoBlueMarketParams CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Coinbase.OpenApiClients.Cdp.Models.MorphoBlueMarketParams();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "collateralToken", n => { CollateralToken = n.GetObjectValue<global::Soenneker.Coinbase.OpenApiClients.Cdp.Models.BorrowProductToken>(global::Soenneker.Coinbase.OpenApiClients.Cdp.Models.BorrowProductToken.CreateFromDiscriminatorValue); } },
                { "interestRateModelAddress", n => { InterestRateModelAddress = n.GetStringValue(); } },
                { "lltvBps", n => { LltvBps = n.GetIntValue(); } },
                { "loanToken", n => { LoanToken = n.GetObjectValue<global::Soenneker.Coinbase.OpenApiClients.Cdp.Models.BorrowProductToken>(global::Soenneker.Coinbase.OpenApiClients.Cdp.Models.BorrowProductToken.CreateFromDiscriminatorValue); } },
                { "onchainMarketId", n => { OnchainMarketId = n.GetStringValue(); } },
                { "oracleAddress", n => { OracleAddress = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteObjectValue<global::Soenneker.Coinbase.OpenApiClients.Cdp.Models.BorrowProductToken>("collateralToken", CollateralToken);
            writer.WriteStringValue("interestRateModelAddress", InterestRateModelAddress);
            writer.WriteIntValue("lltvBps", LltvBps);
            writer.WriteObjectValue<global::Soenneker.Coinbase.OpenApiClients.Cdp.Models.BorrowProductToken>("loanToken", LoanToken);
            writer.WriteStringValue("onchainMarketId", OnchainMarketId);
            writer.WriteStringValue("oracleAddress", OracleAddress);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
