// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Coinbase.OpenApiClients.Cdp.Models
{
    /// <summary>The type of payment method to be used to complete an onramp order.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum OnrampOrderPaymentMethodTypeId
    {
        [EnumMember(Value = "GUEST_CHECKOUT_APPLE_PAY")]
        #pragma warning disable CS1591
        GUEST_CHECKOUT_APPLE_PAY,
        #pragma warning restore CS1591
        [EnumMember(Value = "GUEST_CHECKOUT_GOOGLE_PAY")]
        #pragma warning disable CS1591
        GUEST_CHECKOUT_GOOGLE_PAY,
        #pragma warning restore CS1591
    }
}
