// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Coinbase.OpenApiClients.Cdp.Models
{
    /// <summary>Current status of the transaction.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum OnrampTransactionPayloadStatus
    {
        [EnumMember(Value = "ONRAMP_TRANSACTION_STATUS_UNSPECIFIED")]
        #pragma warning disable CS1591
        OnrampTransactionStatusUnspecified,
        #pragma warning restore CS1591
        [EnumMember(Value = "ONRAMP_TRANSACTION_STATUS_CREATED")]
        #pragma warning disable CS1591
        OnrampTransactionStatusCreated,
        #pragma warning restore CS1591
        [EnumMember(Value = "ONRAMP_TRANSACTION_STATUS_IN_PROGRESS")]
        #pragma warning disable CS1591
        OnrampTransactionStatusInProgress,
        #pragma warning restore CS1591
        [EnumMember(Value = "ONRAMP_TRANSACTION_STATUS_SUCCESS")]
        #pragma warning disable CS1591
        OnrampTransactionStatusSuccess,
        #pragma warning restore CS1591
        [EnumMember(Value = "ONRAMP_TRANSACTION_STATUS_FAILED")]
        #pragma warning disable CS1591
        OnrampTransactionStatusFailed,
        #pragma warning restore CS1591
        [EnumMember(Value = "ONRAMP_TRANSACTION_STATUS_AWAITING_AUTH")]
        #pragma warning disable CS1591
        OnrampTransactionStatusAwaitingAuth,
        #pragma warning restore CS1591
        [EnumMember(Value = "ONRAMP_TRANSACTION_STATUS_AWAITING_PAYMENT")]
        #pragma warning disable CS1591
        OnrampTransactionStatusAwaitingPayment,
        #pragma warning restore CS1591
    }
}
