// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Coinbase.OpenApiClients.Cdp.Models
{
    /// <summary>
    /// A fee associated with a Headless Onramp API order.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class OrderFee : IAdditionalDataHolder, IParsable
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The amount of the fee.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? FeeAmount { get; set; }
#nullable restore
#else
        public string FeeAmount { get; set; }
#endif
        /// <summary>The currency of the fee.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? FeeCurrency { get; set; }
#nullable restore
#else
        public string FeeCurrency { get; set; }
#endif
        /// <summary>The type of fee.</summary>
        public global::Soenneker.Coinbase.OpenApiClients.Cdp.Models.OrderFeeFeeType? FeeType { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Coinbase.OpenApiClients.Cdp.Models.OrderFee"/> and sets the default values.
        /// </summary>
        public OrderFee()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Coinbase.OpenApiClients.Cdp.Models.OrderFee"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Coinbase.OpenApiClients.Cdp.Models.OrderFee CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Coinbase.OpenApiClients.Cdp.Models.OrderFee();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "feeAmount", n => { FeeAmount = n.GetStringValue(); } },
                { "feeCurrency", n => { FeeCurrency = n.GetStringValue(); } },
                { "feeType", n => { FeeType = n.GetEnumValue<global::Soenneker.Coinbase.OpenApiClients.Cdp.Models.OrderFeeFeeType>(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("feeAmount", FeeAmount);
            writer.WriteStringValue("feeCurrency", FeeCurrency);
            writer.WriteEnumValue<global::Soenneker.Coinbase.OpenApiClients.Cdp.Models.OrderFeeFeeType>("feeType", FeeType);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
