// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Coinbase.OpenApiClients.Cdp.Models
{
    /// <summary>
    /// A summary of the payment session included in webhook payloads. Contains the session identity, amount, asset, payer and recipient information, execution behavior, expiry deadlines, current status, running balance totals, and any metadata originally provided when the session was created.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class PaymentSessionSummary : IAdditionalDataHolder, IParsable
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>A decimal representation of the payment amount, denominated in `asset`.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Amount { get; set; }
#nullable restore
#else
        public string Amount { get; set; }
#endif
        /// <summary>The symbol of the asset (e.g., eth, usd, usdc, usdt).</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Asset { get; set; }
#nullable restore
#else
        public string Asset { get; set; }
#endif
        /// <summary>When true, a capture is automatically created after a successful authorization.</summary>
        public bool? AutoCapture { get; set; }
        /// <summary>Running balance totals for the payment session at the time the event was emitted.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Coinbase.OpenApiClients.Cdp.Models.PaymentSessionSummaryBalances? Balances { get; set; }
#nullable restore
#else
        public global::Soenneker.Coinbase.OpenApiClients.Cdp.Models.PaymentSessionSummaryBalances Balances { get; set; }
#endif
        /// <summary>The UTC ISO 8601 timestamp at which the payment session was created.</summary>
        public DateTimeOffset? CreatedAt { get; set; }
        /// <summary>Merchant-provided display data shown to the payer during checkout. All fields are informational only — stored and returned as-is, with no effect on payment processing, settlement, or validation.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Coinbase.OpenApiClients.Cdp.Models.CustomerDisplay? CustomerDisplay { get; set; }
#nullable restore
#else
        public global::Soenneker.Coinbase.OpenApiClients.Cdp.Models.CustomerDisplay CustomerDisplay { get; set; }
#endif
        /// <summary>The ID of the entity that owns the payment session.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? EntityId { get; set; }
#nullable restore
#else
        public string EntityId { get; set; }
#endif
        /// <summary>Deadline timestamps for authorization, capture, and refund windows.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Coinbase.OpenApiClients.Cdp.Models.PaymentSessionSummaryExpiries? Expiries { get; set; }
#nullable restore
#else
        public global::Soenneker.Coinbase.OpenApiClients.Cdp.Models.PaymentSessionSummaryExpiries Expiries { get; set; }
#endif
        /// <summary>A merchant-provided internal identifier for this payment session, from the merchant&apos;s own system—not visible to the payer. It must not contain personally identifiable information (PII) or payment credentials.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ExternalReferenceId { get; set; }
#nullable restore
#else
        public string ExternalReferenceId { get; set; }
#endif
        /// <summary>Optional metadata as key-value pairs. Use this to store additional structured information on a resource, such as customer IDs, order references, or any application-specific data. Up to 10 key/value pairs may be provided. Keys and values are both strings. Keys must be ≤ 40 characters; values must be ≤ 500 characters.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Coinbase.OpenApiClients.Cdp.Models.PaymentSessionSummaryMetadata? Metadata { get; set; }
#nullable restore
#else
        public global::Soenneker.Coinbase.OpenApiClients.Cdp.Models.PaymentSessionSummaryMetadata Metadata { get; set; }
#endif
        /// <summary>The ID of the payment session, a UUID prefixed by `paymentSession_`.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? PaymentSessionId { get; set; }
#nullable restore
#else
        public string PaymentSessionId { get; set; }
#endif
        /// <summary>The payer&apos;s address and network. Set after a successful authorization. Not present before authorization.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Coinbase.OpenApiClients.Cdp.Models.PaymentSessionSummarySource? Source { get; set; }
#nullable restore
#else
        public global::Soenneker.Coinbase.OpenApiClients.Cdp.Models.PaymentSessionSummarySource Source { get; set; }
#endif
        /// <summary>The current status of the payment session at the time the event was emitted.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Coinbase.OpenApiClients.Cdp.Models.PaymentSessionSummaryStatus? Status { get; set; }
#nullable restore
#else
        public global::Soenneker.Coinbase.OpenApiClients.Cdp.Models.PaymentSessionSummaryStatus Status { get; set; }
#endif
        /// <summary>The recipient of the payment.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Coinbase.OpenApiClients.Cdp.Models.PaymentSessionSummaryTarget? Target { get; set; }
#nullable restore
#else
        public global::Soenneker.Coinbase.OpenApiClients.Cdp.Models.PaymentSessionSummaryTarget Target { get; set; }
#endif
        /// <summary>The UTC ISO 8601 timestamp at which the payment session was last updated.</summary>
        public DateTimeOffset? UpdatedAt { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Coinbase.OpenApiClients.Cdp.Models.PaymentSessionSummary"/> and sets the default values.
        /// </summary>
        public PaymentSessionSummary()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Coinbase.OpenApiClients.Cdp.Models.PaymentSessionSummary"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Coinbase.OpenApiClients.Cdp.Models.PaymentSessionSummary CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Coinbase.OpenApiClients.Cdp.Models.PaymentSessionSummary();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "amount", n => { Amount = n.GetStringValue(); } },
                { "asset", n => { Asset = n.GetStringValue(); } },
                { "autoCapture", n => { AutoCapture = n.GetBoolValue(); } },
                { "balances", n => { Balances = n.GetObjectValue<global::Soenneker.Coinbase.OpenApiClients.Cdp.Models.PaymentSessionSummaryBalances>(global::Soenneker.Coinbase.OpenApiClients.Cdp.Models.PaymentSessionSummaryBalances.CreateFromDiscriminatorValue); } },
                { "createdAt", n => { CreatedAt = n.GetDateTimeOffsetValue(); } },
                { "customerDisplay", n => { CustomerDisplay = n.GetObjectValue<global::Soenneker.Coinbase.OpenApiClients.Cdp.Models.CustomerDisplay>(global::Soenneker.Coinbase.OpenApiClients.Cdp.Models.CustomerDisplay.CreateFromDiscriminatorValue); } },
                { "entityId", n => { EntityId = n.GetStringValue(); } },
                { "expiries", n => { Expiries = n.GetObjectValue<global::Soenneker.Coinbase.OpenApiClients.Cdp.Models.PaymentSessionSummaryExpiries>(global::Soenneker.Coinbase.OpenApiClients.Cdp.Models.PaymentSessionSummaryExpiries.CreateFromDiscriminatorValue); } },
                { "externalReferenceId", n => { ExternalReferenceId = n.GetStringValue(); } },
                { "metadata", n => { Metadata = n.GetObjectValue<global::Soenneker.Coinbase.OpenApiClients.Cdp.Models.PaymentSessionSummaryMetadata>(global::Soenneker.Coinbase.OpenApiClients.Cdp.Models.PaymentSessionSummaryMetadata.CreateFromDiscriminatorValue); } },
                { "paymentSessionId", n => { PaymentSessionId = n.GetStringValue(); } },
                { "source", n => { Source = n.GetObjectValue<global::Soenneker.Coinbase.OpenApiClients.Cdp.Models.PaymentSessionSummarySource>(global::Soenneker.Coinbase.OpenApiClients.Cdp.Models.PaymentSessionSummarySource.CreateFromDiscriminatorValue); } },
                { "status", n => { Status = n.GetObjectValue<global::Soenneker.Coinbase.OpenApiClients.Cdp.Models.PaymentSessionSummaryStatus>(global::Soenneker.Coinbase.OpenApiClients.Cdp.Models.PaymentSessionSummaryStatus.CreateFromDiscriminatorValue); } },
                { "target", n => { Target = n.GetObjectValue<global::Soenneker.Coinbase.OpenApiClients.Cdp.Models.PaymentSessionSummaryTarget>(global::Soenneker.Coinbase.OpenApiClients.Cdp.Models.PaymentSessionSummaryTarget.CreateFromDiscriminatorValue); } },
                { "updatedAt", n => { UpdatedAt = n.GetDateTimeOffsetValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("amount", Amount);
            writer.WriteStringValue("asset", Asset);
            writer.WriteBoolValue("autoCapture", AutoCapture);
            writer.WriteObjectValue<global::Soenneker.Coinbase.OpenApiClients.Cdp.Models.PaymentSessionSummaryBalances>("balances", Balances);
            writer.WriteDateTimeOffsetValue("createdAt", CreatedAt);
            writer.WriteObjectValue<global::Soenneker.Coinbase.OpenApiClients.Cdp.Models.CustomerDisplay>("customerDisplay", CustomerDisplay);
            writer.WriteStringValue("entityId", EntityId);
            writer.WriteObjectValue<global::Soenneker.Coinbase.OpenApiClients.Cdp.Models.PaymentSessionSummaryExpiries>("expiries", Expiries);
            writer.WriteStringValue("externalReferenceId", ExternalReferenceId);
            writer.WriteObjectValue<global::Soenneker.Coinbase.OpenApiClients.Cdp.Models.PaymentSessionSummaryMetadata>("metadata", Metadata);
            writer.WriteStringValue("paymentSessionId", PaymentSessionId);
            writer.WriteObjectValue<global::Soenneker.Coinbase.OpenApiClients.Cdp.Models.PaymentSessionSummarySource>("source", Source);
            writer.WriteObjectValue<global::Soenneker.Coinbase.OpenApiClients.Cdp.Models.PaymentSessionSummaryStatus>("status", Status);
            writer.WriteObjectValue<global::Soenneker.Coinbase.OpenApiClients.Cdp.Models.PaymentSessionSummaryTarget>("target", Target);
            writer.WriteDateTimeOffsetValue("updatedAt", UpdatedAt);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
