// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Coinbase.OpenApiClients.Cdp.Models
{
    /// <summary>The blockchain network supported for payment session targets. Testnet networks are only available in sandbox environments.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum PaymentTargetNetwork
    {
        [EnumMember(Value = "base")]
        #pragma warning disable CS1591
        BaseValue,
        #pragma warning restore CS1591
        [EnumMember(Value = "base-sepolia")]
        #pragma warning disable CS1591
        BaseSepolia,
        #pragma warning restore CS1591
    }
}
