// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Coinbase.OpenApiClients.Cdp.Models
{
    /// <summary>
    /// Present when the event was triggered by an authorization status transition (`pending`, `succeeded`, or `failed`).
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class PaymentSessionEventDataAuthorization : IAdditionalDataHolder, IParsable
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>A decimal representation of the authorized amount, denominated in the session&apos;s `asset`.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Amount { get; set; }
#nullable restore
#else
        public string Amount { get; set; }
#endif
        /// <summary>The ID of the authorization, a UUID prefixed by `authorization_`.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? AuthorizationId { get; set; }
#nullable restore
#else
        public string AuthorizationId { get; set; }
#endif
        /// <summary>The UTC ISO 8601 timestamp at which the authorization was created.</summary>
        public DateTimeOffset? CreatedAt { get; set; }
        /// <summary>Customer-facing display data for this authorization, shown to the payer. Present when supplied on the authorization request or when the session&apos;s `orderCode` fallback applies; otherwise omitted.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Coinbase.OpenApiClients.Cdp.Models.PaymentSessionEventDataAuthorizationCustomerDisplay? CustomerDisplay { get; set; }
#nullable restore
#else
        public global::Soenneker.Coinbase.OpenApiClients.Cdp.Models.PaymentSessionEventDataAuthorizationCustomerDisplay CustomerDisplay { get; set; }
#endif
        /// <summary>Error details, present only when the authorization failed.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Coinbase.OpenApiClients.Cdp.Models.PaymentSessionEventDataAuthorizationError? Error { get; set; }
#nullable restore
#else
        public global::Soenneker.Coinbase.OpenApiClients.Cdp.Models.PaymentSessionEventDataAuthorizationError Error { get; set; }
#endif
        /// <summary>A merchant-provided internal identifier for a resource from the merchant&apos;s own system—not visible to the payer. It must not contain personally identifiable information (PII) or payment credentials.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ExternalReferenceId { get; set; }
#nullable restore
#else
        public string ExternalReferenceId { get; set; }
#endif
        /// <summary>Optional metadata as key-value pairs. Use this to store additional structured information on a resource, such as customer IDs, order references, or any application-specific data. Up to 10 key/value pairs may be provided. Keys and values are both strings. Keys must be ≤ 40 characters; values must be ≤ 500 characters.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Coinbase.OpenApiClients.Cdp.Models.PaymentSessionEventDataAuthorizationMetadata? Metadata { get; set; }
#nullable restore
#else
        public global::Soenneker.Coinbase.OpenApiClients.Cdp.Models.PaymentSessionEventDataAuthorizationMetadata Metadata { get; set; }
#endif
        /// <summary>The onchain transactions associated with this authorization.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Coinbase.OpenApiClients.Cdp.Models.OnchainTransaction>? OnchainTransactions { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Coinbase.OpenApiClients.Cdp.Models.OnchainTransaction> OnchainTransactions { get; set; }
#endif
        /// <summary>The payer for this authorization. For wallet authorizations, this is the blockchain address that signed the payloads. For Coinbase authorizations, this is the authenticated Coinbase account.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Coinbase.OpenApiClients.Cdp.Models.PaymentSessionEventDataAuthorizationSource? Source { get; set; }
#nullable restore
#else
        public global::Soenneker.Coinbase.OpenApiClients.Cdp.Models.PaymentSessionEventDataAuthorizationSource Source { get; set; }
#endif
        /// <summary>The current status of the authorization.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Coinbase.OpenApiClients.Cdp.Models.PaymentSessionEventDataAuthorizationStatus? Status { get; set; }
#nullable restore
#else
        public global::Soenneker.Coinbase.OpenApiClients.Cdp.Models.PaymentSessionEventDataAuthorizationStatus Status { get; set; }
#endif
        /// <summary>The UTC ISO 8601 timestamp at which the authorization was last updated.</summary>
        public DateTimeOffset? UpdatedAt { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Coinbase.OpenApiClients.Cdp.Models.PaymentSessionEventDataAuthorization"/> and sets the default values.
        /// </summary>
        public PaymentSessionEventDataAuthorization()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Coinbase.OpenApiClients.Cdp.Models.PaymentSessionEventDataAuthorization"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Coinbase.OpenApiClients.Cdp.Models.PaymentSessionEventDataAuthorization CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Coinbase.OpenApiClients.Cdp.Models.PaymentSessionEventDataAuthorization();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "amount", n => { Amount = n.GetStringValue(); } },
                { "authorizationId", n => { AuthorizationId = n.GetStringValue(); } },
                { "createdAt", n => { CreatedAt = n.GetDateTimeOffsetValue(); } },
                { "customerDisplay", n => { CustomerDisplay = n.GetObjectValue<global::Soenneker.Coinbase.OpenApiClients.Cdp.Models.PaymentSessionEventDataAuthorizationCustomerDisplay>(global::Soenneker.Coinbase.OpenApiClients.Cdp.Models.PaymentSessionEventDataAuthorizationCustomerDisplay.CreateFromDiscriminatorValue); } },
                { "error", n => { Error = n.GetObjectValue<global::Soenneker.Coinbase.OpenApiClients.Cdp.Models.PaymentSessionEventDataAuthorizationError>(global::Soenneker.Coinbase.OpenApiClients.Cdp.Models.PaymentSessionEventDataAuthorizationError.CreateFromDiscriminatorValue); } },
                { "externalReferenceId", n => { ExternalReferenceId = n.GetStringValue(); } },
                { "metadata", n => { Metadata = n.GetObjectValue<global::Soenneker.Coinbase.OpenApiClients.Cdp.Models.PaymentSessionEventDataAuthorizationMetadata>(global::Soenneker.Coinbase.OpenApiClients.Cdp.Models.PaymentSessionEventDataAuthorizationMetadata.CreateFromDiscriminatorValue); } },
                { "onchainTransactions", n => { OnchainTransactions = n.GetCollectionOfObjectValues<global::Soenneker.Coinbase.OpenApiClients.Cdp.Models.OnchainTransaction>(global::Soenneker.Coinbase.OpenApiClients.Cdp.Models.OnchainTransaction.CreateFromDiscriminatorValue)?.AsList(); } },
                { "source", n => { Source = n.GetObjectValue<global::Soenneker.Coinbase.OpenApiClients.Cdp.Models.PaymentSessionEventDataAuthorizationSource>(global::Soenneker.Coinbase.OpenApiClients.Cdp.Models.PaymentSessionEventDataAuthorizationSource.CreateFromDiscriminatorValue); } },
                { "status", n => { Status = n.GetObjectValue<global::Soenneker.Coinbase.OpenApiClients.Cdp.Models.PaymentSessionEventDataAuthorizationStatus>(global::Soenneker.Coinbase.OpenApiClients.Cdp.Models.PaymentSessionEventDataAuthorizationStatus.CreateFromDiscriminatorValue); } },
                { "updatedAt", n => { UpdatedAt = n.GetDateTimeOffsetValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("amount", Amount);
            writer.WriteStringValue("authorizationId", AuthorizationId);
            writer.WriteDateTimeOffsetValue("createdAt", CreatedAt);
            writer.WriteObjectValue<global::Soenneker.Coinbase.OpenApiClients.Cdp.Models.PaymentSessionEventDataAuthorizationCustomerDisplay>("customerDisplay", CustomerDisplay);
            writer.WriteObjectValue<global::Soenneker.Coinbase.OpenApiClients.Cdp.Models.PaymentSessionEventDataAuthorizationError>("error", Error);
            writer.WriteStringValue("externalReferenceId", ExternalReferenceId);
            writer.WriteObjectValue<global::Soenneker.Coinbase.OpenApiClients.Cdp.Models.PaymentSessionEventDataAuthorizationMetadata>("metadata", Metadata);
            writer.WriteCollectionOfObjectValues<global::Soenneker.Coinbase.OpenApiClients.Cdp.Models.OnchainTransaction>("onchainTransactions", OnchainTransactions);
            writer.WriteObjectValue<global::Soenneker.Coinbase.OpenApiClients.Cdp.Models.PaymentSessionEventDataAuthorizationSource>("source", Source);
            writer.WriteObjectValue<global::Soenneker.Coinbase.OpenApiClients.Cdp.Models.PaymentSessionEventDataAuthorizationStatus>("status", Status);
            writer.WriteDateTimeOffsetValue("updatedAt", UpdatedAt);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
