// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Coinbase.OpenApiClients.Cdp.Models
{
    /// <summary>The operation to which the rule applies. Every element of the `criteria` array must match the specified operation.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum PrepareUserOperationRule_operation
    {
        [EnumMember(Value = "prepareUserOperation")]
        #pragma warning disable CS1591
        PrepareUserOperation,
        #pragma warning restore CS1591
    }
}
