// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Coinbase.OpenApiClients.Cdp.Models
{
    /// <summary>
    /// A record of a wallet revocation: the customer removing the mandate&apos;s spending allowance on-chain (see `onchainTransactions`). While it is confirming, the mandate&apos;s `status` is `revocation_pending`; on success it becomes `revocation_succeeded` and the mandate&apos;s `revokedAt` is set, and on failure it becomes `revocation_failed`. This applies regardless of whether the mandate was previously canceled: a revocation on an already-canceled mandate still moves `status` through the `revocation_*` values and sets `revokedAt`.To check whether the spending allowance is still active, read the mandate: `revokedAt` is set once the allowance has been removed.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class Revocation : IAdditionalDataHolder, IParsable
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The UTC ISO 8601 timestamp at which the revocation was created.</summary>
        public DateTimeOffset? CreatedAt { get; set; }
        /// <summary>Details of why the revocation failed. Only present when `status` is `failed`.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Coinbase.OpenApiClients.Cdp.Models.RevocationError? Error { get; set; }
#nullable restore
#else
        public global::Soenneker.Coinbase.OpenApiClients.Cdp.Models.RevocationError Error { get; set; }
#endif
        /// <summary>The ID of the mandate, a UUID prefixed by `mandate_`.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? MandateId { get; set; }
#nullable restore
#else
        public string MandateId { get; set; }
#endif
        /// <summary>Optional metadata as key-value pairs. Use this to store additional structured information on a resource, such as customer IDs, order references, or any application-specific data. Up to 10 key/value pairs may be provided. Keys and values are both strings. Keys must be ≤ 40 characters; values must be ≤ 500 characters.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Coinbase.OpenApiClients.Cdp.Models.RevocationMetadata? Metadata { get; set; }
#nullable restore
#else
        public global::Soenneker.Coinbase.OpenApiClients.Cdp.Models.RevocationMetadata Metadata { get; set; }
#endif
        /// <summary>Network transactions that remove the spending allowance on-chain. Empty until the revocation has been submitted to the network.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Coinbase.OpenApiClients.Cdp.Models.OnchainTransaction>? OnchainTransactions { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Coinbase.OpenApiClients.Cdp.Models.OnchainTransaction> OnchainTransactions { get; set; }
#endif
        /// <summary>The ID of a revocation, a UUID prefixed by `revocation_`.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? RevocationId { get; set; }
#nullable restore
#else
        public string RevocationId { get; set; }
#endif
        /// <summary>The current status of the revocation attempt.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Coinbase.OpenApiClients.Cdp.Models.RevocationStatusComposed? Status { get; set; }
#nullable restore
#else
        public global::Soenneker.Coinbase.OpenApiClients.Cdp.Models.RevocationStatusComposed Status { get; set; }
#endif
        /// <summary>The UTC ISO 8601 timestamp at which the revocation was last updated.</summary>
        public DateTimeOffset? UpdatedAt { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Coinbase.OpenApiClients.Cdp.Models.Revocation"/> and sets the default values.
        /// </summary>
        public Revocation()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Coinbase.OpenApiClients.Cdp.Models.Revocation"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Coinbase.OpenApiClients.Cdp.Models.Revocation CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Coinbase.OpenApiClients.Cdp.Models.Revocation();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "createdAt", n => { CreatedAt = n.GetDateTimeOffsetValue(); } },
                { "error", n => { Error = n.GetObjectValue<global::Soenneker.Coinbase.OpenApiClients.Cdp.Models.RevocationError>(global::Soenneker.Coinbase.OpenApiClients.Cdp.Models.RevocationError.CreateFromDiscriminatorValue); } },
                { "mandateId", n => { MandateId = n.GetStringValue(); } },
                { "metadata", n => { Metadata = n.GetObjectValue<global::Soenneker.Coinbase.OpenApiClients.Cdp.Models.RevocationMetadata>(global::Soenneker.Coinbase.OpenApiClients.Cdp.Models.RevocationMetadata.CreateFromDiscriminatorValue); } },
                { "onchainTransactions", n => { OnchainTransactions = n.GetCollectionOfObjectValues<global::Soenneker.Coinbase.OpenApiClients.Cdp.Models.OnchainTransaction>(global::Soenneker.Coinbase.OpenApiClients.Cdp.Models.OnchainTransaction.CreateFromDiscriminatorValue)?.AsList(); } },
                { "revocationId", n => { RevocationId = n.GetStringValue(); } },
                { "status", n => { Status = n.GetObjectValue<global::Soenneker.Coinbase.OpenApiClients.Cdp.Models.RevocationStatusComposed>(global::Soenneker.Coinbase.OpenApiClients.Cdp.Models.RevocationStatusComposed.CreateFromDiscriminatorValue); } },
                { "updatedAt", n => { UpdatedAt = n.GetDateTimeOffsetValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteDateTimeOffsetValue("createdAt", CreatedAt);
            writer.WriteObjectValue<global::Soenneker.Coinbase.OpenApiClients.Cdp.Models.RevocationError>("error", Error);
            writer.WriteStringValue("mandateId", MandateId);
            writer.WriteObjectValue<global::Soenneker.Coinbase.OpenApiClients.Cdp.Models.RevocationMetadata>("metadata", Metadata);
            writer.WriteCollectionOfObjectValues<global::Soenneker.Coinbase.OpenApiClients.Cdp.Models.OnchainTransaction>("onchainTransactions", OnchainTransactions);
            writer.WriteStringValue("revocationId", RevocationId);
            writer.WriteObjectValue<global::Soenneker.Coinbase.OpenApiClients.Cdp.Models.RevocationStatusComposed>("status", Status);
            writer.WriteDateTimeOffsetValue("updatedAt", UpdatedAt);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
