// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Coinbase.OpenApiClients.Cdp.Models
{
    /// <summary>The payment rail for this payment method.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum SepaPaymentMethod_paymentRail
    {
        [EnumMember(Value = "sepa")]
        #pragma warning disable CS1591
        Sepa,
        #pragma warning restore CS1591
    }
}
