// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Coinbase.OpenApiClients.Cdp.Models
{
    /// <summary>
    /// The complete x402 payment required response body from the resource server. Top-level fields (x402Version, resource, error, extensions) are preserved in the signed payment payload; acceptsIndex selects which entry from accepts is signed as paymentPayload.accepted.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class SignSolanaX402PaymentWithEndUserAccountRequestPaymentRequired : IAdditionalDataHolder, IParsable
    {
        /// <summary>The list of payment options the resource server accepts. At least one option must be present.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Coinbase.OpenApiClients.Cdp.Models.X402PaymentRequirements>? Accepts { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Coinbase.OpenApiClients.Cdp.Models.X402PaymentRequirements> Accepts { get; set; }
#endif
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>An optional error message from the resource server describing why payment is required.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Error { get; set; }
#nullable restore
#else
        public string Error { get; set; }
#endif
        /// <summary>Optional protocol extensions. Unknown keys are forwarded as-is into the signed payment payload.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Coinbase.OpenApiClients.Cdp.Models.SignSolanaX402PaymentWithEndUserAccountRequestPaymentRequiredExtensions? Extensions { get; set; }
#nullable restore
#else
        public global::Soenneker.Coinbase.OpenApiClients.Cdp.Models.SignSolanaX402PaymentWithEndUserAccountRequestPaymentRequiredExtensions Extensions { get; set; }
#endif
        /// <summary>Optional metadata about the resource being paid for.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Coinbase.OpenApiClients.Cdp.Models.X402PaymentRequiredResource? Resource { get; set; }
#nullable restore
#else
        public global::Soenneker.Coinbase.OpenApiClients.Cdp.Models.X402PaymentRequiredResource Resource { get; set; }
#endif
        /// <summary>The x402 protocol version.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Coinbase.OpenApiClients.Cdp.Models.X402PaymentRequiredX402Version? X402Version { get; set; }
#nullable restore
#else
        public global::Soenneker.Coinbase.OpenApiClients.Cdp.Models.X402PaymentRequiredX402Version X402Version { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Coinbase.OpenApiClients.Cdp.Models.SignSolanaX402PaymentWithEndUserAccountRequestPaymentRequired"/> and sets the default values.
        /// </summary>
        public SignSolanaX402PaymentWithEndUserAccountRequestPaymentRequired()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Coinbase.OpenApiClients.Cdp.Models.SignSolanaX402PaymentWithEndUserAccountRequestPaymentRequired"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Coinbase.OpenApiClients.Cdp.Models.SignSolanaX402PaymentWithEndUserAccountRequestPaymentRequired CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Coinbase.OpenApiClients.Cdp.Models.SignSolanaX402PaymentWithEndUserAccountRequestPaymentRequired();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "accepts", n => { Accepts = n.GetCollectionOfObjectValues<global::Soenneker.Coinbase.OpenApiClients.Cdp.Models.X402PaymentRequirements>(global::Soenneker.Coinbase.OpenApiClients.Cdp.Models.X402PaymentRequirements.CreateFromDiscriminatorValue)?.AsList(); } },
                { "error", n => { Error = n.GetStringValue(); } },
                { "extensions", n => { Extensions = n.GetObjectValue<global::Soenneker.Coinbase.OpenApiClients.Cdp.Models.SignSolanaX402PaymentWithEndUserAccountRequestPaymentRequiredExtensions>(global::Soenneker.Coinbase.OpenApiClients.Cdp.Models.SignSolanaX402PaymentWithEndUserAccountRequestPaymentRequiredExtensions.CreateFromDiscriminatorValue); } },
                { "resource", n => { Resource = n.GetObjectValue<global::Soenneker.Coinbase.OpenApiClients.Cdp.Models.X402PaymentRequiredResource>(global::Soenneker.Coinbase.OpenApiClients.Cdp.Models.X402PaymentRequiredResource.CreateFromDiscriminatorValue); } },
                { "x402Version", n => { X402Version = n.GetObjectValue<global::Soenneker.Coinbase.OpenApiClients.Cdp.Models.X402PaymentRequiredX402Version>(global::Soenneker.Coinbase.OpenApiClients.Cdp.Models.X402PaymentRequiredX402Version.CreateFromDiscriminatorValue); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteCollectionOfObjectValues<global::Soenneker.Coinbase.OpenApiClients.Cdp.Models.X402PaymentRequirements>("accepts", Accepts);
            writer.WriteStringValue("error", Error);
            writer.WriteObjectValue<global::Soenneker.Coinbase.OpenApiClients.Cdp.Models.SignSolanaX402PaymentWithEndUserAccountRequestPaymentRequiredExtensions>("extensions", Extensions);
            writer.WriteObjectValue<global::Soenneker.Coinbase.OpenApiClients.Cdp.Models.X402PaymentRequiredResource>("resource", Resource);
            writer.WriteObjectValue<global::Soenneker.Coinbase.OpenApiClients.Cdp.Models.X402PaymentRequiredX402Version>("x402Version", X402Version);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
