// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Coinbase.OpenApiClients.Cdp.Models
{
    /// <summary>The operator to use for the comparison. The transaction instruction&apos;s `value` field will be on the left-hand side of the operator, and the `solValue` field will be on the right-hand side.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum SolValueCriterion_operator
    {
        [EnumMember(Value = ">")]
        #pragma warning disable CS1591
        GreaterThan,
        #pragma warning restore CS1591
        [EnumMember(Value = ">=")]
        #pragma warning disable CS1591
        GreaterThanOrEqual,
        #pragma warning restore CS1591
        [EnumMember(Value = "<")]
        #pragma warning disable CS1591
        LessThan,
        #pragma warning restore CS1591
        [EnumMember(Value = "<=")]
        #pragma warning disable CS1591
        LessThanOrEqual,
        #pragma warning restore CS1591
        [EnumMember(Value = "==")]
        #pragma warning disable CS1591
        DoubleEqual,
        #pragma warning restore CS1591
    }
}
