// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Coinbase.OpenApiClients.Cdp.Models
{
    /// <summary>&quot;Specifies whether the given amount is to be received by the target or taken from the source.- `target`: The transfer `target` receives the exact value specified in `amount`. Fees are added to the amount taken from the transfer `source`.- `source`: The transfer `target` receives the value specified in `amount`, minus any fees.&quot;</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum TransferRequest_amountType
    {
        [EnumMember(Value = "target")]
        #pragma warning disable CS1591
        Target,
        #pragma warning restore CS1591
        [EnumMember(Value = "source")]
        #pragma warning disable CS1591
        Source,
        #pragma warning restore CS1591
    }
}
