// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Coinbase.OpenApiClients.Cdp.Models
{
    /// <summary>The type of bank account, based on the account identification scheme (e.g., `us_bank`).</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum UsBankAccountType
    {
        [EnumMember(Value = "us_bank")]
        #pragma warning disable CS1591
        UsBank,
        #pragma warning restore CS1591
    }
}
