// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Coinbase.OpenApiClients.Cdp.Models
{
    /// <summary>
    /// The x402 protocol payment payload that the client attaches to x402-paid API requests to the resource server in the X-PAYMENT header.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class X402V2PaymentPayload : IAdditionalDataHolder, IParsable
    {
        /// <summary>The x402 protocol payment requirements that the resource server expects the client&apos;s payment payload to meet.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Coinbase.OpenApiClients.Cdp.Models.X402V2PaymentRequirements? Accepted { get; set; }
#nullable restore
#else
        public global::Soenneker.Coinbase.OpenApiClients.Cdp.Models.X402V2PaymentRequirements Accepted { get; set; }
#endif
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>Optional protocol extensions.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Coinbase.OpenApiClients.Cdp.Models.X402V2PaymentPayload_extensions? Extensions { get; set; }
#nullable restore
#else
        public global::Soenneker.Coinbase.OpenApiClients.Cdp.Models.X402V2PaymentPayload_extensions Extensions { get; set; }
#endif
        /// <summary>The payload of the payment depending on the x402Version, scheme, and network.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Coinbase.OpenApiClients.Cdp.Models.X402V2PaymentPayload.X402V2PaymentPayload_payload? Payload { get; set; }
#nullable restore
#else
        public global::Soenneker.Coinbase.OpenApiClients.Cdp.Models.X402V2PaymentPayload.X402V2PaymentPayload_payload Payload { get; set; }
#endif
        /// <summary>Describes the resource being accessed in x402 protocol.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Coinbase.OpenApiClients.Cdp.Models.X402ResourceInfo? Resource { get; set; }
#nullable restore
#else
        public global::Soenneker.Coinbase.OpenApiClients.Cdp.Models.X402ResourceInfo Resource { get; set; }
#endif
        /// <summary>The version of the x402 protocol.</summary>
        public int? X402Version { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Coinbase.OpenApiClients.Cdp.Models.X402V2PaymentPayload"/> and sets the default values.
        /// </summary>
        public X402V2PaymentPayload()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Coinbase.OpenApiClients.Cdp.Models.X402V2PaymentPayload"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Coinbase.OpenApiClients.Cdp.Models.X402V2PaymentPayload CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Coinbase.OpenApiClients.Cdp.Models.X402V2PaymentPayload();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "accepted", n => { Accepted = n.GetObjectValue<global::Soenneker.Coinbase.OpenApiClients.Cdp.Models.X402V2PaymentRequirements>(global::Soenneker.Coinbase.OpenApiClients.Cdp.Models.X402V2PaymentRequirements.CreateFromDiscriminatorValue); } },
                { "extensions", n => { Extensions = n.GetObjectValue<global::Soenneker.Coinbase.OpenApiClients.Cdp.Models.X402V2PaymentPayload_extensions>(global::Soenneker.Coinbase.OpenApiClients.Cdp.Models.X402V2PaymentPayload_extensions.CreateFromDiscriminatorValue); } },
                { "payload", n => { Payload = n.GetObjectValue<global::Soenneker.Coinbase.OpenApiClients.Cdp.Models.X402V2PaymentPayload.X402V2PaymentPayload_payload>(global::Soenneker.Coinbase.OpenApiClients.Cdp.Models.X402V2PaymentPayload.X402V2PaymentPayload_payload.CreateFromDiscriminatorValue); } },
                { "resource", n => { Resource = n.GetObjectValue<global::Soenneker.Coinbase.OpenApiClients.Cdp.Models.X402ResourceInfo>(global::Soenneker.Coinbase.OpenApiClients.Cdp.Models.X402ResourceInfo.CreateFromDiscriminatorValue); } },
                { "x402Version", n => { X402Version = n.GetIntValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteObjectValue<global::Soenneker.Coinbase.OpenApiClients.Cdp.Models.X402V2PaymentRequirements>("accepted", Accepted);
            writer.WriteObjectValue<global::Soenneker.Coinbase.OpenApiClients.Cdp.Models.X402V2PaymentPayload_extensions>("extensions", Extensions);
            writer.WriteObjectValue<global::Soenneker.Coinbase.OpenApiClients.Cdp.Models.X402V2PaymentPayload.X402V2PaymentPayload_payload>("payload", Payload);
            writer.WriteObjectValue<global::Soenneker.Coinbase.OpenApiClients.Cdp.Models.X402ResourceInfo>("resource", Resource);
            writer.WriteIntValue("x402Version", X402Version);
            writer.WriteAdditionalData(AdditionalData);
        }
        /// <summary>
        /// Composed type wrapper for classes <see cref="global::Soenneker.Coinbase.OpenApiClients.Cdp.Models.X402ExactEvmPayload"/>, <see cref="global::Soenneker.Coinbase.OpenApiClients.Cdp.Models.X402ExactEvmPermit2Payload"/>, <see cref="global::Soenneker.Coinbase.OpenApiClients.Cdp.Models.X402ExactSolanaPayload"/>
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class X402V2PaymentPayload_payload : IComposedTypeWrapper, IParsable
        {
            /// <summary>Composed type representation for type <see cref="global::Soenneker.Coinbase.OpenApiClients.Cdp.Models.X402ExactEvmPayload"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::Soenneker.Coinbase.OpenApiClients.Cdp.Models.X402ExactEvmPayload? X402ExactEvmPayload { get; set; }
#nullable restore
#else
            public global::Soenneker.Coinbase.OpenApiClients.Cdp.Models.X402ExactEvmPayload X402ExactEvmPayload { get; set; }
#endif
            /// <summary>Composed type representation for type <see cref="global::Soenneker.Coinbase.OpenApiClients.Cdp.Models.X402ExactEvmPermit2Payload"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::Soenneker.Coinbase.OpenApiClients.Cdp.Models.X402ExactEvmPermit2Payload? X402ExactEvmPermit2Payload { get; set; }
#nullable restore
#else
            public global::Soenneker.Coinbase.OpenApiClients.Cdp.Models.X402ExactEvmPermit2Payload X402ExactEvmPermit2Payload { get; set; }
#endif
            /// <summary>Composed type representation for type <see cref="global::Soenneker.Coinbase.OpenApiClients.Cdp.Models.X402ExactSolanaPayload"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::Soenneker.Coinbase.OpenApiClients.Cdp.Models.X402ExactSolanaPayload? X402ExactSolanaPayload { get; set; }
#nullable restore
#else
            public global::Soenneker.Coinbase.OpenApiClients.Cdp.Models.X402ExactSolanaPayload X402ExactSolanaPayload { get; set; }
#endif
            /// <summary>
            /// Creates a new instance of the appropriate class based on discriminator value
            /// </summary>
            /// <returns>A <see cref="global::Soenneker.Coinbase.OpenApiClients.Cdp.Models.X402V2PaymentPayload.X402V2PaymentPayload_payload"/></returns>
            /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
            public static global::Soenneker.Coinbase.OpenApiClients.Cdp.Models.X402V2PaymentPayload.X402V2PaymentPayload_payload CreateFromDiscriminatorValue(IParseNode parseNode)
            {
                if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
                var mappingValue = parseNode.GetChildNode("")?.GetStringValue();
                var result = new global::Soenneker.Coinbase.OpenApiClients.Cdp.Models.X402V2PaymentPayload.X402V2PaymentPayload_payload();
                if("x402ExactEvmPayload".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
                {
                    result.X402ExactEvmPayload = new global::Soenneker.Coinbase.OpenApiClients.Cdp.Models.X402ExactEvmPayload();
                }
                else if("x402ExactEvmPermit2Payload".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
                {
                    result.X402ExactEvmPermit2Payload = new global::Soenneker.Coinbase.OpenApiClients.Cdp.Models.X402ExactEvmPermit2Payload();
                }
                else if("x402ExactSolanaPayload".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
                {
                    result.X402ExactSolanaPayload = new global::Soenneker.Coinbase.OpenApiClients.Cdp.Models.X402ExactSolanaPayload();
                }
                return result;
            }
            /// <summary>
            /// The deserialization information for the current model
            /// </summary>
            /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
            public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
            {
                if(X402ExactEvmPayload != null)
                {
                    return X402ExactEvmPayload.GetFieldDeserializers();
                }
                else if(X402ExactEvmPermit2Payload != null)
                {
                    return X402ExactEvmPermit2Payload.GetFieldDeserializers();
                }
                else if(X402ExactSolanaPayload != null)
                {
                    return X402ExactSolanaPayload.GetFieldDeserializers();
                }
                return new Dictionary<string, Action<IParseNode>>();
            }
            /// <summary>
            /// Serializes information the current object
            /// </summary>
            /// <param name="writer">Serialization writer to use to serialize this model</param>
            public virtual void Serialize(ISerializationWriter writer)
            {
                if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
                if(X402ExactEvmPayload != null)
                {
                    writer.WriteObjectValue<global::Soenneker.Coinbase.OpenApiClients.Cdp.Models.X402ExactEvmPayload>(null, X402ExactEvmPayload);
                }
                else if(X402ExactEvmPermit2Payload != null)
                {
                    writer.WriteObjectValue<global::Soenneker.Coinbase.OpenApiClients.Cdp.Models.X402ExactEvmPermit2Payload>(null, X402ExactEvmPermit2Payload);
                }
                else if(X402ExactSolanaPayload != null)
                {
                    writer.WriteObjectValue<global::Soenneker.Coinbase.OpenApiClients.Cdp.Models.X402ExactSolanaPayload>(null, X402ExactSolanaPayload);
                }
            }
        }
    }
}
#pragma warning restore CS0618
