// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Coinbase.OpenApiClients.Cdp.Models
{
    /// <summary>
    /// Composed type wrapper for classes <see cref="global::Soenneker.Coinbase.OpenApiClients.Cdp.Models.X402ExactEvmPayload_1"/>, <see cref="global::Soenneker.Coinbase.OpenApiClients.Cdp.Models.X402ExactEvmPermit2Payload_1"/>, <see cref="global::Soenneker.Coinbase.OpenApiClients.Cdp.Models.X402ExactSolanaPayload_1"/>
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class X402V2PaymentPayload1Payload : IComposedTypeWrapper, IParsable
    {
        /// <summary>Composed type representation for type <see cref="global::Soenneker.Coinbase.OpenApiClients.Cdp.Models.X402ExactEvmPayload_1"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Coinbase.OpenApiClients.Cdp.Models.X402ExactEvmPayload_1? X402ExactEvmPayload1 { get; set; }
#nullable restore
#else
        public global::Soenneker.Coinbase.OpenApiClients.Cdp.Models.X402ExactEvmPayload_1 X402ExactEvmPayload1 { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::Soenneker.Coinbase.OpenApiClients.Cdp.Models.X402ExactEvmPermit2Payload_1"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Coinbase.OpenApiClients.Cdp.Models.X402ExactEvmPermit2Payload_1? X402ExactEvmPermit2Payload1 { get; set; }
#nullable restore
#else
        public global::Soenneker.Coinbase.OpenApiClients.Cdp.Models.X402ExactEvmPermit2Payload_1 X402ExactEvmPermit2Payload1 { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::Soenneker.Coinbase.OpenApiClients.Cdp.Models.X402ExactSolanaPayload_1"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Coinbase.OpenApiClients.Cdp.Models.X402ExactSolanaPayload_1? X402ExactSolanaPayload1 { get; set; }
#nullable restore
#else
        public global::Soenneker.Coinbase.OpenApiClients.Cdp.Models.X402ExactSolanaPayload_1 X402ExactSolanaPayload1 { get; set; }
#endif
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Coinbase.OpenApiClients.Cdp.Models.X402V2PaymentPayload1Payload"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Coinbase.OpenApiClients.Cdp.Models.X402V2PaymentPayload1Payload CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            var mappingValue = parseNode.GetChildNode("type")?.GetStringValue();
            var result = new global::Soenneker.Coinbase.OpenApiClients.Cdp.Models.X402V2PaymentPayload1Payload();
            if("X402ExactEvmPayload_1".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
            {
                result.X402ExactEvmPayload1 = new global::Soenneker.Coinbase.OpenApiClients.Cdp.Models.X402ExactEvmPayload_1();
            }
            else if("X402ExactEvmPermit2Payload_1".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
            {
                result.X402ExactEvmPermit2Payload1 = new global::Soenneker.Coinbase.OpenApiClients.Cdp.Models.X402ExactEvmPermit2Payload_1();
            }
            else if("X402ExactSolanaPayload_1".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
            {
                result.X402ExactSolanaPayload1 = new global::Soenneker.Coinbase.OpenApiClients.Cdp.Models.X402ExactSolanaPayload_1();
            }
            return result;
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            if(X402ExactEvmPayload1 != null)
            {
                return X402ExactEvmPayload1.GetFieldDeserializers();
            }
            else if(X402ExactEvmPermit2Payload1 != null)
            {
                return X402ExactEvmPermit2Payload1.GetFieldDeserializers();
            }
            else if(X402ExactSolanaPayload1 != null)
            {
                return X402ExactSolanaPayload1.GetFieldDeserializers();
            }
            return new Dictionary<string, Action<IParseNode>>();
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            if(X402ExactEvmPayload1 != null)
            {
                writer.WriteObjectValue<global::Soenneker.Coinbase.OpenApiClients.Cdp.Models.X402ExactEvmPayload_1>(null, X402ExactEvmPayload1);
            }
            else if(X402ExactEvmPermit2Payload1 != null)
            {
                writer.WriteObjectValue<global::Soenneker.Coinbase.OpenApiClients.Cdp.Models.X402ExactEvmPermit2Payload_1>(null, X402ExactEvmPermit2Payload1);
            }
            else if(X402ExactSolanaPayload1 != null)
            {
                writer.WriteObjectValue<global::Soenneker.Coinbase.OpenApiClients.Cdp.Models.X402ExactSolanaPayload_1>(null, X402ExactSolanaPayload1);
            }
        }
    }
}
#pragma warning restore CS0618
