// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Coinbase.OpenApiClients.Cdp.Models
{
    /// <summary>The HTTP method used to probe the endpoint. Only GET and POST are supported; other verbs are intentionally rejected because x402 resources are expected to respond to these methods.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum X402ValidateRequestMethod
    {
        [EnumMember(Value = "GET")]
        #pragma warning disable CS1591
        Get,
        #pragma warning restore CS1591
        [EnumMember(Value = "POST")]
        #pragma warning disable CS1591
        Post,
        #pragma warning restore CS1591
    }
}
