// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using Soenneker.Coinbase.OpenApiClients.Cdp.V2.Evm.Eip7702.DelegationOperations.Item;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Soenneker.Coinbase.OpenApiClients.Cdp.V2.Evm.Eip7702.DelegationOperations
{
    /// <summary>
    /// Builds and executes requests for operations under \v2\evm\eip7702\delegation-operations
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class DelegationOperationsRequestBuilder : BaseRequestBuilder
    {
        /// <summary>Gets an item from the Soenneker.Coinbase.OpenApiClients.Cdp.v2.evm.eip7702.delegationOperations.item collection</summary>
        /// <param name="position">The unique identifier for the delegation operation.</param>
        /// <returns>A <see cref="global::Soenneker.Coinbase.OpenApiClients.Cdp.V2.Evm.Eip7702.DelegationOperations.Item.WithDelegationOperationItemRequestBuilder"/></returns>
        public global::Soenneker.Coinbase.OpenApiClients.Cdp.V2.Evm.Eip7702.DelegationOperations.Item.WithDelegationOperationItemRequestBuilder this[Guid position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                urlTplParams.Add("delegationOperationId", position);
                return new global::Soenneker.Coinbase.OpenApiClients.Cdp.V2.Evm.Eip7702.DelegationOperations.Item.WithDelegationOperationItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>Gets an item from the Soenneker.Coinbase.OpenApiClients.Cdp.v2.evm.eip7702.delegationOperations.item collection</summary>
        /// <param name="position">The unique identifier for the delegation operation.</param>
        /// <returns>A <see cref="global::Soenneker.Coinbase.OpenApiClients.Cdp.V2.Evm.Eip7702.DelegationOperations.Item.WithDelegationOperationItemRequestBuilder"/></returns>
        [Obsolete("This indexer is deprecated and will be removed in the next major version. Use the one with the typed parameter instead.")]
        public global::Soenneker.Coinbase.OpenApiClients.Cdp.V2.Evm.Eip7702.DelegationOperations.Item.WithDelegationOperationItemRequestBuilder this[string position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                if (!string.IsNullOrWhiteSpace(position)) urlTplParams.Add("delegationOperationId", position);
                return new global::Soenneker.Coinbase.OpenApiClients.Cdp.V2.Evm.Eip7702.DelegationOperations.Item.WithDelegationOperationItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Coinbase.OpenApiClients.Cdp.V2.Evm.Eip7702.DelegationOperations.DelegationOperationsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public DelegationOperationsRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/v2/evm/eip7702/delegation-operations", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Coinbase.OpenApiClients.Cdp.V2.Evm.Eip7702.DelegationOperations.DelegationOperationsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public DelegationOperationsRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/v2/evm/eip7702/delegation-operations", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
