// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using Soenneker.Coinbase.OpenApiClients.Cdp.V2.X402.Settle;
using Soenneker.Coinbase.OpenApiClients.Cdp.V2.X402.Supported;
using Soenneker.Coinbase.OpenApiClients.Cdp.V2.X402.Verify;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Soenneker.Coinbase.OpenApiClients.Cdp.V2.X402
{
    /// <summary>
    /// Builds and executes requests for operations under \v2\x402
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class X402RequestBuilder : BaseRequestBuilder
    {
        /// <summary>The settle property</summary>
        public global::Soenneker.Coinbase.OpenApiClients.Cdp.V2.X402.Settle.SettleRequestBuilder Settle
        {
            get => new global::Soenneker.Coinbase.OpenApiClients.Cdp.V2.X402.Settle.SettleRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The supported property</summary>
        public global::Soenneker.Coinbase.OpenApiClients.Cdp.V2.X402.Supported.SupportedRequestBuilder Supported
        {
            get => new global::Soenneker.Coinbase.OpenApiClients.Cdp.V2.X402.Supported.SupportedRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The verify property</summary>
        public global::Soenneker.Coinbase.OpenApiClients.Cdp.V2.X402.Verify.VerifyRequestBuilder Verify
        {
            get => new global::Soenneker.Coinbase.OpenApiClients.Cdp.V2.X402.Verify.VerifyRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Coinbase.OpenApiClients.Cdp.V2.X402.X402RequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public X402RequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/v2/x402", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Coinbase.OpenApiClients.Cdp.V2.X402.X402RequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public X402RequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/v2/x402", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
