// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using Soenneker.Coinbase.OpenApiClients.Cdp.V2.EmbeddedWalletApi.Evm.BorrowProducts;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Soenneker.Coinbase.OpenApiClients.Cdp.V2.EmbeddedWalletApi.Evm
{
    /// <summary>
    /// Builds and executes requests for operations under \v2\embedded-wallet-api\evm
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class EvmRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The borrowProducts property</summary>
        public global::Soenneker.Coinbase.OpenApiClients.Cdp.V2.EmbeddedWalletApi.Evm.BorrowProducts.BorrowProductsRequestBuilder BorrowProducts
        {
            get => new global::Soenneker.Coinbase.OpenApiClients.Cdp.V2.EmbeddedWalletApi.Evm.BorrowProducts.BorrowProductsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Coinbase.OpenApiClients.Cdp.V2.EmbeddedWalletApi.Evm.EvmRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public EvmRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/v2/embedded-wallet-api/evm", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Coinbase.OpenApiClients.Cdp.V2.EmbeddedWalletApi.Evm.EvmRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public EvmRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/v2/embedded-wallet-api/evm", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
