// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using Soenneker.Coinbase.OpenApiClients.Cdp.Models;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace Soenneker.Coinbase.OpenApiClients.Cdp.V2.X402.Discovery.Search
{
    /// <summary>
    /// Builds and executes requests for operations under \v2\x402\discovery\search
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class SearchRequestBuilder : BaseRequestBuilder
    {
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Coinbase.OpenApiClients.Cdp.V2.X402.Discovery.Search.SearchRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public SearchRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/v2/x402/discovery/search{?asset*,extensions*,limit*,maxUsdPrice*,network*,payTo*,query*,scheme*,urlSubstring*}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Coinbase.OpenApiClients.Cdp.V2.X402.Discovery.Search.SearchRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public SearchRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/v2/x402/discovery/search{?asset*,extensions*,limit*,maxUsdPrice*,network*,payTo*,query*,scheme*,urlSubstring*}", rawUrl)
        {
        }
        /// <summary>
        /// Searches for active x402 resources using a text query and optional filters.Supports both text-based and vector-based search depending on availability. Results are sorted by relevance and quality score.Legacy network names (e.g., `base`, `base-sepolia`, `solana`) are automatically normalized to their CAIP-2 equivalents.The response is limited to 20 items per request. If more results exist, `partialResults` will be `true`.
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Coinbase.OpenApiClients.Cdp.Models.X402SearchResourcesResponse"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::Soenneker.Coinbase.OpenApiClients.Cdp.Models.Error">When receiving a 400 status code</exception>
        /// <exception cref="global::Soenneker.Coinbase.OpenApiClients.Cdp.Models.Error">When receiving a 500 status code</exception>
        /// <exception cref="global::Soenneker.Coinbase.OpenApiClients.Cdp.Models.Error">When receiving a 502 status code</exception>
        /// <exception cref="global::Soenneker.Coinbase.OpenApiClients.Cdp.Models.Error">When receiving a 503 status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::Soenneker.Coinbase.OpenApiClients.Cdp.Models.X402SearchResourcesResponse?> GetAsync(Action<RequestConfiguration<global::Soenneker.Coinbase.OpenApiClients.Cdp.V2.X402.Discovery.Search.SearchRequestBuilder.SearchRequestBuilderGetQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::Soenneker.Coinbase.OpenApiClients.Cdp.Models.X402SearchResourcesResponse> GetAsync(Action<RequestConfiguration<global::Soenneker.Coinbase.OpenApiClients.Cdp.V2.X402.Discovery.Search.SearchRequestBuilder.SearchRequestBuilderGetQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "400", global::Soenneker.Coinbase.OpenApiClients.Cdp.Models.Error.CreateFromDiscriminatorValue },
                { "500", global::Soenneker.Coinbase.OpenApiClients.Cdp.Models.Error.CreateFromDiscriminatorValue },
                { "502", global::Soenneker.Coinbase.OpenApiClients.Cdp.Models.Error.CreateFromDiscriminatorValue },
                { "503", global::Soenneker.Coinbase.OpenApiClients.Cdp.Models.Error.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<global::Soenneker.Coinbase.OpenApiClients.Cdp.Models.X402SearchResourcesResponse>(requestInfo, global::Soenneker.Coinbase.OpenApiClients.Cdp.Models.X402SearchResourcesResponse.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Searches for active x402 resources using a text query and optional filters.Supports both text-based and vector-based search depending on availability. Results are sorted by relevance and quality score.Legacy network names (e.g., `base`, `base-sepolia`, `solana`) are automatically normalized to their CAIP-2 equivalents.The response is limited to 20 items per request. If more results exist, `partialResults` will be `true`.
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::Soenneker.Coinbase.OpenApiClients.Cdp.V2.X402.Discovery.Search.SearchRequestBuilder.SearchRequestBuilderGetQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::Soenneker.Coinbase.OpenApiClients.Cdp.V2.X402.Discovery.Search.SearchRequestBuilder.SearchRequestBuilderGetQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.GET, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Coinbase.OpenApiClients.Cdp.V2.X402.Discovery.Search.SearchRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::Soenneker.Coinbase.OpenApiClients.Cdp.V2.X402.Discovery.Search.SearchRequestBuilder WithUrl(string rawUrl)
        {
            return new global::Soenneker.Coinbase.OpenApiClients.Cdp.V2.X402.Discovery.Search.SearchRequestBuilder(rawUrl, RequestAdapter);
        }
        /// <summary>
        /// Searches for active x402 resources using a text query and optional filters.Supports both text-based and vector-based search depending on availability. Results are sorted by relevance and quality score.Legacy network names (e.g., `base`, `base-sepolia`, `solana`) are automatically normalized to their CAIP-2 equivalents.The response is limited to 20 items per request. If more results exist, `partialResults` will be `true`.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class SearchRequestBuilderGetQueryParameters 
        {
            /// <summary>Filter results by asset address.For EVM networks, provide a 0x-prefixed EVM address. For Solana networks, provide a base58-encoded address.Matching is case-insensitive.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("asset")]
            public string? Asset { get; set; }
#nullable restore
#else
            [QueryParameter("asset")]
            public string Asset { get; set; }
#endif
            /// <summary>Filter results to resources that support the specified protocol extensions. Can be specified multiple times to filter by multiple extensions.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("extensions")]
            public string[]? Extensions { get; set; }
#nullable restore
#else
            [QueryParameter("extensions")]
            public string[] Extensions { get; set; }
#endif
            /// <summary>Maximum number of resources to return. Must be a positive integer no greater than 20.Defaults to 20.</summary>
            [QueryParameter("limit")]
            public int? Limit { get; set; }
            /// <summary>Filter results to resources with a USD price at or below this value.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("maxUsdPrice")]
            public string? MaxUsdPrice { get; set; }
#nullable restore
#else
            [QueryParameter("maxUsdPrice")]
            public string MaxUsdPrice { get; set; }
#endif
            /// <summary>Filter results by network in CAIP-2 format (e.g., `eip155:8453`) or legacy name (e.g., `base`, `base-sepolia`, `solana`).Legacy names are normalized to their CAIP-2 equivalents before filtering.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("network")]
            public string? Network { get; set; }
#nullable restore
#else
            [QueryParameter("network")]
            public string Network { get; set; }
#endif
            /// <summary>Filter results by the merchant&apos;s payment address.For EVM networks, provide a 0x-prefixed EVM address. For Solana networks, provide a base58-encoded address.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("payTo")]
            public string? PayTo { get; set; }
#nullable restore
#else
            [QueryParameter("payTo")]
            public string PayTo { get; set; }
#endif
            /// <summary>Full-text or semantic search query to find matching resources.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("query")]
            public string? Query { get; set; }
#nullable restore
#else
            [QueryParameter("query")]
            public string Query { get; set; }
#endif
            /// <summary>Filter results by payment scheme (e.g., `exact`).</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("scheme")]
            public string? Scheme { get; set; }
#nullable restore
#else
            [QueryParameter("scheme")]
            public string Scheme { get; set; }
#endif
            /// <summary>&quot;Filter results to resources whose URL contains this value (case-insensitive substring match against the resource URL).Useful for narrowing results to a specific domain, subdomain, or path segment. Combine with `query` to perform semantic search restricted to a URL subset.Tip: include enough of the URL to disambiguate (e.g. `api.example.com` rather than `example`) — a short substring may also match resources whose path contains the same string.&quot;</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("urlSubstring")]
            public string? UrlSubstring { get; set; }
#nullable restore
#else
            [QueryParameter("urlSubstring")]
            public string UrlSubstring { get; set; }
#endif
        }
    }
}
#pragma warning restore CS0618
