// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using Soenneker.Coinbase.OpenApiClients.Cdp.V2.Evm.Accounts.Item.Send.Transaction;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Soenneker.Coinbase.OpenApiClients.Cdp.V2.Evm.Accounts.Item.Send
{
    /// <summary>
    /// Builds and executes requests for operations under \v2\evm\accounts\{address}\send
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class SendRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The transaction property</summary>
        public global::Soenneker.Coinbase.OpenApiClients.Cdp.V2.Evm.Accounts.Item.Send.Transaction.TransactionRequestBuilder Transaction
        {
            get => new global::Soenneker.Coinbase.OpenApiClients.Cdp.V2.Evm.Accounts.Item.Send.Transaction.TransactionRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Coinbase.OpenApiClients.Cdp.V2.Evm.Accounts.Item.Send.SendRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public SendRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/v2/evm/accounts/{address}/send", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Coinbase.OpenApiClients.Cdp.V2.Evm.Accounts.Item.Send.SendRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public SendRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/v2/evm/accounts/{address}/send", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
