// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using Soenneker.Coinbase.OpenApiClients.Cdp.V2.X402.Discovery.Mcp;
using Soenneker.Coinbase.OpenApiClients.Cdp.V2.X402.Discovery.Merchant;
using Soenneker.Coinbase.OpenApiClients.Cdp.V2.X402.Discovery.Resources;
using Soenneker.Coinbase.OpenApiClients.Cdp.V2.X402.Discovery.Search;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Soenneker.Coinbase.OpenApiClients.Cdp.V2.X402.Discovery
{
    /// <summary>
    /// Builds and executes requests for operations under \v2\x402\discovery
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class DiscoveryRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The mcp property</summary>
        public global::Soenneker.Coinbase.OpenApiClients.Cdp.V2.X402.Discovery.Mcp.McpRequestBuilder Mcp
        {
            get => new global::Soenneker.Coinbase.OpenApiClients.Cdp.V2.X402.Discovery.Mcp.McpRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The merchant property</summary>
        public global::Soenneker.Coinbase.OpenApiClients.Cdp.V2.X402.Discovery.Merchant.MerchantRequestBuilder Merchant
        {
            get => new global::Soenneker.Coinbase.OpenApiClients.Cdp.V2.X402.Discovery.Merchant.MerchantRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The resources property</summary>
        public global::Soenneker.Coinbase.OpenApiClients.Cdp.V2.X402.Discovery.Resources.ResourcesRequestBuilder Resources
        {
            get => new global::Soenneker.Coinbase.OpenApiClients.Cdp.V2.X402.Discovery.Resources.ResourcesRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The search property</summary>
        public global::Soenneker.Coinbase.OpenApiClients.Cdp.V2.X402.Discovery.Search.SearchRequestBuilder Search
        {
            get => new global::Soenneker.Coinbase.OpenApiClients.Cdp.V2.X402.Discovery.Search.SearchRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Coinbase.OpenApiClients.Cdp.V2.X402.Discovery.DiscoveryRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public DiscoveryRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/v2/x402/discovery", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Coinbase.OpenApiClients.Cdp.V2.X402.Discovery.DiscoveryRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public DiscoveryRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/v2/x402/discovery", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
