// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Coinbase.OpenApiClients.Cdp.Models
{
    /// <summary>
    /// ABI function type for contract functions.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class AbiFunction : IAdditionalDataHolder, IParsable
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>Deprecated. Use pure or view from stateMutability instead.</summary>
        public bool? Constant { get; set; }
        /// <summary>Deprecated. Vyper used to provide gas estimates.</summary>
        public int? Gas { get; set; }
        /// <summary>The list of ABI parameters used for this function.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Coinbase.OpenApiClients.Cdp.Models.AbiParameter>? Inputs { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Coinbase.OpenApiClients.Cdp.Models.AbiParameter> Inputs { get; set; }
#endif
        /// <summary>The name of the ABI function.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Name { get; set; }
#nullable restore
#else
        public string Name { get; set; }
#endif
        /// <summary>The values returned by this function.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Coinbase.OpenApiClients.Cdp.Models.AbiParameter>? Outputs { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Coinbase.OpenApiClients.Cdp.Models.AbiParameter> Outputs { get; set; }
#endif
        /// <summary>Deprecated. Use payable or nonpayable from `stateMutability` instead.</summary>
        public bool? Payable { get; set; }
        /// <summary>State mutability of a function in Solidity.</summary>
        public global::Soenneker.Coinbase.OpenApiClients.Cdp.Models.AbiStateMutability? StateMutability { get; set; }
        /// <summary>The type of the ABI item, must be `function`.</summary>
        public global::Soenneker.Coinbase.OpenApiClients.Cdp.Models.AbiFunction_type? Type { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Coinbase.OpenApiClients.Cdp.Models.AbiFunction"/> and sets the default values.
        /// </summary>
        public AbiFunction()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Coinbase.OpenApiClients.Cdp.Models.AbiFunction"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Coinbase.OpenApiClients.Cdp.Models.AbiFunction CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Coinbase.OpenApiClients.Cdp.Models.AbiFunction();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "constant", n => { Constant = n.GetBoolValue(); } },
                { "gas", n => { Gas = n.GetIntValue(); } },
                { "inputs", n => { Inputs = n.GetCollectionOfObjectValues<global::Soenneker.Coinbase.OpenApiClients.Cdp.Models.AbiParameter>(global::Soenneker.Coinbase.OpenApiClients.Cdp.Models.AbiParameter.CreateFromDiscriminatorValue)?.AsList(); } },
                { "name", n => { Name = n.GetStringValue(); } },
                { "outputs", n => { Outputs = n.GetCollectionOfObjectValues<global::Soenneker.Coinbase.OpenApiClients.Cdp.Models.AbiParameter>(global::Soenneker.Coinbase.OpenApiClients.Cdp.Models.AbiParameter.CreateFromDiscriminatorValue)?.AsList(); } },
                { "payable", n => { Payable = n.GetBoolValue(); } },
                { "stateMutability", n => { StateMutability = n.GetEnumValue<global::Soenneker.Coinbase.OpenApiClients.Cdp.Models.AbiStateMutability>(); } },
                { "type", n => { Type = n.GetEnumValue<global::Soenneker.Coinbase.OpenApiClients.Cdp.Models.AbiFunction_type>(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteBoolValue("constant", Constant);
            writer.WriteIntValue("gas", Gas);
            writer.WriteCollectionOfObjectValues<global::Soenneker.Coinbase.OpenApiClients.Cdp.Models.AbiParameter>("inputs", Inputs);
            writer.WriteStringValue("name", Name);
            writer.WriteCollectionOfObjectValues<global::Soenneker.Coinbase.OpenApiClients.Cdp.Models.AbiParameter>("outputs", Outputs);
            writer.WriteBoolValue("payable", Payable);
            writer.WriteEnumValue<global::Soenneker.Coinbase.OpenApiClients.Cdp.Models.AbiStateMutability>("stateMutability", StateMutability);
            writer.WriteEnumValue<global::Soenneker.Coinbase.OpenApiClients.Cdp.Models.AbiFunction_type>("type", Type);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
