// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Coinbase.OpenApiClients.Cdp.Models
{
    /// <summary>The type of criterion to use. This should be `evmData`.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum EvmDataCriterion_type
    {
        [EnumMember(Value = "evmData")]
        #pragma warning disable CS1591
        EvmData,
        #pragma warning restore CS1591
    }
}
