// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Coinbase.OpenApiClients.Cdp.Models
{
    /// <summary>The type of payment method used to generate the onramp quote.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum OnrampQuotePaymentMethodTypeId
    {
        [EnumMember(Value = "CARD")]
        #pragma warning disable CS1591
        CARD,
        #pragma warning restore CS1591
        [EnumMember(Value = "ACH")]
        #pragma warning disable CS1591
        ACH,
        #pragma warning restore CS1591
        [EnumMember(Value = "APPLE_PAY")]
        #pragma warning disable CS1591
        APPLE_PAY,
        #pragma warning restore CS1591
        [EnumMember(Value = "PAYPAL")]
        #pragma warning disable CS1591
        PAYPAL,
        #pragma warning restore CS1591
        [EnumMember(Value = "FIAT_WALLET")]
        #pragma warning disable CS1591
        FIAT_WALLET,
        #pragma warning restore CS1591
        [EnumMember(Value = "CRYPTO_WALLET")]
        #pragma warning disable CS1591
        CRYPTO_WALLET,
        #pragma warning restore CS1591
    }
}
