// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Coinbase.OpenApiClients.Cdp.Models
{
    /// <summary>
    /// Quote information with pricing details for the crypto purchase.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class OnrampQuote : IAdditionalDataHolder, IParsable
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The network to send the crypto on.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? DestinationNetwork { get; set; }
#nullable restore
#else
        public string DestinationNetwork { get; set; }
#endif
        /// <summary>The exchange rate used to convert fiat to crypto i.e. the crypto value of one fiat.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ExchangeRate { get; set; }
#nullable restore
#else
        public string ExchangeRate { get; set; }
#endif
        /// <summary>The fees associated with the quote.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Coinbase.OpenApiClients.Cdp.Models.OnrampOrderFee>? Fees { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Coinbase.OpenApiClients.Cdp.Models.OnrampOrderFee> Fees { get; set; }
#endif
        /// <summary>The fiat currency to be converted to crypto.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? PaymentCurrency { get; set; }
#nullable restore
#else
        public string PaymentCurrency { get; set; }
#endif
        /// <summary>The amount of fiat to be converted to crypto.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? PaymentSubtotal { get; set; }
#nullable restore
#else
        public string PaymentSubtotal { get; set; }
#endif
        /// <summary>The total amount of fiat to be paid, inclusive of any fees.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? PaymentTotal { get; set; }
#nullable restore
#else
        public string PaymentTotal { get; set; }
#endif
        /// <summary>The amount of crypto to be purchased.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? PurchaseAmount { get; set; }
#nullable restore
#else
        public string PurchaseAmount { get; set; }
#endif
        /// <summary>The crypto currency to be purchased.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? PurchaseCurrency { get; set; }
#nullable restore
#else
        public string PurchaseCurrency { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Coinbase.OpenApiClients.Cdp.Models.OnrampQuote"/> and sets the default values.
        /// </summary>
        public OnrampQuote()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Coinbase.OpenApiClients.Cdp.Models.OnrampQuote"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Coinbase.OpenApiClients.Cdp.Models.OnrampQuote CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Coinbase.OpenApiClients.Cdp.Models.OnrampQuote();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "destinationNetwork", n => { DestinationNetwork = n.GetStringValue(); } },
                { "exchangeRate", n => { ExchangeRate = n.GetStringValue(); } },
                { "fees", n => { Fees = n.GetCollectionOfObjectValues<global::Soenneker.Coinbase.OpenApiClients.Cdp.Models.OnrampOrderFee>(global::Soenneker.Coinbase.OpenApiClients.Cdp.Models.OnrampOrderFee.CreateFromDiscriminatorValue)?.AsList(); } },
                { "paymentCurrency", n => { PaymentCurrency = n.GetStringValue(); } },
                { "paymentSubtotal", n => { PaymentSubtotal = n.GetStringValue(); } },
                { "paymentTotal", n => { PaymentTotal = n.GetStringValue(); } },
                { "purchaseAmount", n => { PurchaseAmount = n.GetStringValue(); } },
                { "purchaseCurrency", n => { PurchaseCurrency = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("destinationNetwork", DestinationNetwork);
            writer.WriteStringValue("exchangeRate", ExchangeRate);
            writer.WriteCollectionOfObjectValues<global::Soenneker.Coinbase.OpenApiClients.Cdp.Models.OnrampOrderFee>("fees", Fees);
            writer.WriteStringValue("paymentCurrency", PaymentCurrency);
            writer.WriteStringValue("paymentSubtotal", PaymentSubtotal);
            writer.WriteStringValue("paymentTotal", PaymentTotal);
            writer.WriteStringValue("purchaseAmount", PurchaseAmount);
            writer.WriteStringValue("purchaseCurrency", PurchaseCurrency);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
