// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using Soenneker.Coinbase.OpenApiClients.Cdp.V2.EmbeddedWalletApi.Projects.Item.EndUsers.Item;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Soenneker.Coinbase.OpenApiClients.Cdp.V2.EmbeddedWalletApi.Projects.Item.EndUsers
{
    /// <summary>
    /// Builds and executes requests for operations under \v2\embedded-wallet-api\projects\{projectId}\end-users
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class EndUsersRequestBuilder : BaseRequestBuilder
    {
        /// <summary>Gets an item from the Soenneker.Coinbase.OpenApiClients.Cdp.v2.embeddedWalletApi.projects.item.endUsers.item collection</summary>
        /// <param name="position">The ID of the end user.</param>
        /// <returns>A <see cref="global::Soenneker.Coinbase.OpenApiClients.Cdp.V2.EmbeddedWalletApi.Projects.Item.EndUsers.Item.WithUserItemRequestBuilder"/></returns>
        public global::Soenneker.Coinbase.OpenApiClients.Cdp.V2.EmbeddedWalletApi.Projects.Item.EndUsers.Item.WithUserItemRequestBuilder this[string position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                urlTplParams.Add("userId", position);
                return new global::Soenneker.Coinbase.OpenApiClients.Cdp.V2.EmbeddedWalletApi.Projects.Item.EndUsers.Item.WithUserItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Coinbase.OpenApiClients.Cdp.V2.EmbeddedWalletApi.Projects.Item.EndUsers.EndUsersRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public EndUsersRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/v2/embedded-wallet-api/projects/{projectId}/end-users", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Coinbase.OpenApiClients.Cdp.V2.EmbeddedWalletApi.Projects.Item.EndUsers.EndUsersRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public EndUsersRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/v2/embedded-wallet-api/projects/{projectId}/end-users", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
