// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using Soenneker.Coinbase.OpenApiClients.Cdp.V2.EmbeddedWalletApi.Projects.Item.EndUsers.Item.Evm.Eip7702.Delegation;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Soenneker.Coinbase.OpenApiClients.Cdp.V2.EmbeddedWalletApi.Projects.Item.EndUsers.Item.Evm.Eip7702
{
    /// <summary>
    /// Builds and executes requests for operations under \v2\embedded-wallet-api\projects\{projectId}\end-users\{userId}\evm\eip7702
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class Eip7702RequestBuilder : BaseRequestBuilder
    {
        /// <summary>The delegation property</summary>
        public global::Soenneker.Coinbase.OpenApiClients.Cdp.V2.EmbeddedWalletApi.Projects.Item.EndUsers.Item.Evm.Eip7702.Delegation.DelegationRequestBuilder Delegation
        {
            get => new global::Soenneker.Coinbase.OpenApiClients.Cdp.V2.EmbeddedWalletApi.Projects.Item.EndUsers.Item.Evm.Eip7702.Delegation.DelegationRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Coinbase.OpenApiClients.Cdp.V2.EmbeddedWalletApi.Projects.Item.EndUsers.Item.Evm.Eip7702.Eip7702RequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public Eip7702RequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/v2/embedded-wallet-api/projects/{projectId}/end-users/{userId}/evm/eip7702", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Coinbase.OpenApiClients.Cdp.V2.EmbeddedWalletApi.Projects.Item.EndUsers.Item.Evm.Eip7702.Eip7702RequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public Eip7702RequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/v2/embedded-wallet-api/projects/{projectId}/end-users/{userId}/evm/eip7702", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
